const mongoose = require('mongoose');
require('dotenv').config();
const MedDatabase = require('./models/MedDatabase');

const medicinesData = [
  {
    "medicineName": "Dolo-650",
    "composition": "Paracetamol (650mg)",
    "purpose": "Fever and mild to moderate pain",
    "category": "Painkiller",
    "dosageAdults": "1 tablet every 6 hours if needed",
    "dosageChildren": "",
    "sideEffectsCommon": "Nausea, allergic skin reaction",
    "sideEffectsRare": "",
    "contraindications": "Severe liver disease",
    "prescriptionRequired": false,
    "manufacturer": "Micro Labs Ltd",
    "imageUrl": "https://example.com/images/dolo650.jpg"
  },
  {
    "medicineName": "Augmentin 625 Duo",
    "composition": "Amoxicillin (500mg) + Clavulanic Acid (125mg)",
    "purpose": "Bacterial infections (ear, throat, skin)",
    "category": "Antibiotic",
    "dosageAdults": "1 tablet twice daily after food",
    "dosageChildren": "",
    "sideEffectsCommon": "Diarrhea, vomiting, skin rash",
    "sideEffectsRare": "",
    "contraindications": "Penicillin allergy, liver history",
    "prescriptionRequired": true,
    "manufacturer": "GlaxoSmithKline",
    "imageUrl": "https://example.com/images/augmentin625.jpg"
  },
  {
    "medicineName": "Cetzine",
    "composition": "Cetirizine (10mg)",
    "purpose": "Allergic reactions, runny nose, sneezing",
    "category": "Antihistamine",
    "dosageAdults": "1 tablet at bedtime",
    "dosageChildren": "",
    "sideEffectsCommon": "Drowsiness, dry mouth",
    "sideEffectsRare": "",
    "contraindications": "Severe kidney failure",
    "prescriptionRequired": false,
    "manufacturer": "Dr. Reddy's Laboratories",
    "imageUrl": "https://example.com/images/cetzine.jpg"
  },
  {
    "medicineName": "Pantocid 40",
    "composition": "Pantoprazole (40mg)",
    "purpose": "Acid reflux, GERD, Heartburn",
    "category": "Antacid",
    "dosageAdults": "1 tablet 30 mins before breakfast",
    "dosageChildren": "",
    "sideEffectsCommon": "Headache, flatulence",
    "sideEffectsRare": "",
    "contraindications": "Low magnesium levels",
    "prescriptionRequired": true,
    "manufacturer": "Sun Pharma",
    "imageUrl": "https://example.com/images/pantocid40.jpg"
  },
  {
    "medicineName": "Combiflam",
    "composition": "Ibuprofen (400mg) + Paracetamol (325mg)",
    "purpose": "Muscle pain, toothache, inflammation",
    "category": "Painkiller",
    "dosageAdults": "1 tablet after food, up to 3 times daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Heartburn, stomach pain",
    "sideEffectsRare": "",
    "contraindications": "Stomach ulcers, asthma",
    "prescriptionRequired": false,
    "manufacturer": "Sanofi India",
    "imageUrl": "https://example.com/images/combiflam.jpg"
  },
  {
    "medicineName": "Azithral 500",
    "composition": "Azithromycin (500mg)",
    "purpose": "Respiratory tract infections",
    "category": "Antibiotic",
    "dosageAdults": "1 tablet daily for 3-5 days",
    "dosageChildren": "",
    "sideEffectsCommon": "Abdominal pain, nausea",
    "sideEffectsRare": "",
    "contraindications": "Liver issues, heart rhythm disorders",
    "prescriptionRequired": true,
    "manufacturer": "Alembic Pharmaceuticals",
    "imageUrl": "https://example.com/images/azithral500.jpg"
  },
  {
    "medicineName": "Glycomet-GP 1",
    "composition": "Glimepiride (1mg) + Metformin (500mg)",
    "purpose": "Type 2 Diabetes Mellitus control",
    "category": "Antidiabetic",
    "dosageAdults": "1 tablet before breakfast",
    "dosageChildren": "",
    "sideEffectsCommon": "Hypoglycemia (low sugar), taste change",
    "sideEffectsRare": "",
    "contraindications": "Kidney dysfunction, metabolic acidosis",
    "prescriptionRequired": true,
    "manufacturer": "USV Pvt Ltd",
    "imageUrl": "https://example.com/images/glycomet.jpg"
  },
  {
    "medicineName": "Amlong 5",
    "composition": "Amlodipine (5mg)",
    "purpose": "High Blood Pressure (Hypertension)",
    "category": "Antihypertensive",
    "dosageAdults": "1 tablet daily at fixed time",
    "dosageChildren": "",
    "sideEffectsCommon": "Swelling of ankles, fatigue",
    "sideEffectsRare": "",
    "contraindications": "Low blood pressure, heart failure",
    "prescriptionRequired": true,
    "manufacturer": "Micro Labs Ltd",
    "imageUrl": "https://example.com/images/amlong5.jpg"
  },
  {
    "medicineName": "Becosules",
    "composition": "Vitamin B-Complex + Vitamin C",
    "purpose": "Mouth ulcers, Vitamin deficiency",
    "category": "Vitamin/Supplement",
    "dosageAdults": "1 capsule daily after food",
    "dosageChildren": "",
    "sideEffectsCommon": "Bright yellow urine (harmless)",
    "sideEffectsRare": "",
    "contraindications": "None specifically",
    "prescriptionRequired": false,
    "manufacturer": "Pfizer Ltd",
    "imageUrl": "https://example.com/images/becosules.jpg"
  },
  {
    "medicineName": "Gelusil MPS",
    "composition": "Aluminium Hydroxide + Magnesium Hydroxide",
    "purpose": "Acidity, gas, bloating",
    "category": "Antacid",
    "dosageAdults": "10ml after meals",
    "dosageChildren": "",
    "sideEffectsCommon": "Chalky taste, loose stools",
    "sideEffectsRare": "",
    "contraindications": "Kidney failure",
    "prescriptionRequired": false,
    "manufacturer": "Pfizer Ltd",
    "imageUrl": "https://example.com/images/gelusil.jpg"
  },
  {
    "medicineName": "Allegra 120",
    "composition": "Fexofenadine (120mg)",
    "purpose": "Seasonal allergies, skin itching",
    "category": "Antihistamine",
    "dosageAdults": "1 tablet daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Dizziness, headache",
    "sideEffectsRare": "",
    "contraindications": "Kidney disease",
    "prescriptionRequired": false,
    "manufacturer": "Sanofi India",
    "imageUrl": "https://example.com/images/allegra120.jpg"
  },
  {
    "medicineName": "Ascoril LS",
    "composition": "Levosalbutamol + Ambroxol + Guaiphenesin",
    "purpose": "Wet cough with mucus",
    "category": "Cough & Cold",
    "dosageAdults": "5ml-10ml thrice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Tremors, increased heart rate",
    "sideEffectsRare": "",
    "contraindications": "Heart disease, thyroid disorders",
    "prescriptionRequired": true,
    "manufacturer": "Glenmark Pharmaceuticals",
    "imageUrl": "https://example.com/images/ascoril_ls.jpg"
  },
  {
    "medicineName": "Telma 40",
    "composition": "Telmisartan (40mg)",
    "purpose": "High blood pressure, heart failure prevention",
    "category": "Antihypertensive",
    "dosageAdults": "1 tablet daily in the morning",
    "dosageChildren": "",
    "sideEffectsCommon": "Sinus infection, back pain",
    "sideEffectsRare": "",
    "contraindications": "Pregnancy, severe liver impairment",
    "prescriptionRequired": true,
    "manufacturer": "Glenmark Pharmaceuticals",
    "imageUrl": "https://example.com/images/telma40.jpg"
  },
  {
    "medicineName": "Eltroxin 50mcg",
    "composition": "Thyroxine Sodium (50mcg)",
    "purpose": "Hypothyroidism (Underactive thyroid)",
    "category": "Other",
    "dosageAdults": "1 tablet empty stomach early morning",
    "dosageChildren": "",
    "sideEffectsCommon": "Palpitations, weight loss (if dose too high)",
    "sideEffectsRare": "",
    "contraindications": "Untreated adrenal insufficiency",
    "prescriptionRequired": true,
    "manufacturer": "Abbott",
    "imageUrl": "https://example.com/images/eltroxin.jpg"
  },
  {
    "medicineName": "Shelcal 500",
    "composition": "Calcium (500mg) + Vitamin D3",
    "purpose": "Weak bones, Osteoporosis",
    "category": "Vitamin/Supplement",
    "dosageAdults": "1 tablet daily after main meal",
    "dosageChildren": "",
    "sideEffectsCommon": "Constipation, gas",
    "sideEffectsRare": "",
    "contraindications": "Hypercalcemia (High calcium levels), kidney stones",
    "prescriptionRequired": false,
    "manufacturer": "Torrent Pharmaceuticals",
    "imageUrl": "https://example.com/images/shelcal500.jpg"
  },
  {
    "medicineName": "Omez 20",
    "composition": "Omeprazole (20mg)",
    "purpose": "Gastric ulcers, Acidity",
    "category": "Antacid",
    "dosageAdults": "1 capsule before breakfast",
    "dosageChildren": "",
    "sideEffectsCommon": "Headache, nausea",
    "sideEffectsRare": "",
    "contraindications": "Osteoporosis risk (long term use)",
    "prescriptionRequired": true,
    "manufacturer": "Dr. Reddy's Laboratories",
    "imageUrl": "https://example.com/images/omez20.jpg"
  },
  {
    "medicineName": "Meftal-Spas",
    "composition": "Mefenamic Acid + Dicyclomine",
    "purpose": "Menstrual cramps, stomach pain",
    "category": "Painkiller",
    "dosageAdults": "1 tablet when needed for pain",
    "dosageChildren": "",
    "sideEffectsCommon": "Dizziness, dry mouth",
    "sideEffectsRare": "",
    "contraindications": "Glaucoma, enlarged prostate",
    "prescriptionRequired": false,
    "manufacturer": "Blue Cross Laboratories",
    "imageUrl": "https://example.com/images/meftalspas.jpg"
  },
  {
    "medicineName": "Sinarest",
    "composition": "Paracetamol + Phenylephrine + CPM",
    "purpose": "Common cold, fever, blocked nose",
    "category": "Cough & Cold",
    "dosageAdults": "1 tablet every 6-8 hours",
    "dosageChildren": "",
    "sideEffectsCommon": "Drowsiness, restlessness",
    "sideEffectsRare": "",
    "contraindications": "High BP, hyperthyroidism",
    "prescriptionRequired": false,
    "manufacturer": "Centaur Pharmaceuticals",
    "imageUrl": "https://example.com/images/sinarest.jpg"
  },
  {
    "medicineName": "Electral Powder",
    "composition": "Sodium + Potassium + Dextrose",
    "purpose": "Dehydration due to diarrhea",
    "category": "Gastrointestinal",
    "dosageAdults": "Dissolve sachet in 1L water, drink as needed",
    "dosageChildren": "",
    "sideEffectsCommon": "Vomiting (if drunk too fast)",
    "sideEffectsRare": "",
    "contraindications": "Kidney failure with low urine output",
    "prescriptionRequired": false,
    "manufacturer": "FDC Ltd",
    "imageUrl": "https://example.com/images/electral.jpg"
  },
  {
    "medicineName": "Ciplox 500",
    "composition": "Ciprofloxacin (500mg)",
    "purpose": "Urinary tract infections, Typhoid",
    "category": "Antibiotic",
    "dosageAdults": "1 tablet every 12 hours",
    "dosageChildren": "",
    "sideEffectsCommon": "Nausea, tendon pain",
    "sideEffectsRare": "",
    "contraindications": "Muscle weakness disorders",
    "prescriptionRequired": true,
    "manufacturer": "Cipla Ltd",
    "imageUrl": "https://example.com/images/ciplox500.jpg"
  },
  {
    "medicineName": "Betadine Ointment",
    "composition": "Povidone Iodine (5%)",
    "purpose": "Minor cuts, burns, wounds",
    "category": "Other",
    "dosageAdults": "Apply thinly on wound twice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Skin irritation",
    "sideEffectsRare": "",
    "contraindications": "Thyroid disorders (excessive use)",
    "prescriptionRequired": false,
    "manufacturer": "Win-Medicare",
    "imageUrl": "https://example.com/images/betadine.jpg"
  },
  {
    "medicineName": "Limcee",
    "composition": "Vitamin C (500mg)",
    "purpose": "Immunity booster, Scurvy",
    "category": "Vitamin/Supplement",
    "dosageAdults": "1 tablet (chewable) daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Stomach upset (if overdosed)",
    "sideEffectsRare": "",
    "contraindications": "None specifically",
    "prescriptionRequired": false,
    "manufacturer": "Abbott",
    "imageUrl": "https://example.com/images/limcee.jpg"
  },
  {
    "medicineName": "Atorva 10",
    "composition": "Atorvastatin (10mg)",
    "purpose": "High Cholesterol",
    "category": "Cardiovascular",
    "dosageAdults": "1 tablet at bedtime",
    "dosageChildren": "",
    "sideEffectsCommon": "Muscle pain, digestive issues",
    "sideEffectsRare": "",
    "contraindications": "Active liver disease",
    "prescriptionRequired": true,
    "manufacturer": "Zydus Cadila",
    "imageUrl": "https://example.com/images/atorva10.jpg"
  },
  {
    "medicineName": "Montek-LC",
    "composition": "Montelukast + Levocetirizine",
    "purpose": "Allergic rhinitis, asthma maintenance",
    "category": "Anti-Allergic",
    "dosageAdults": "1 tablet at night",
    "dosageChildren": "",
    "sideEffectsCommon": "Sleepiness, mood changes",
    "sideEffectsRare": "",
    "contraindications": "Severe kidney impairment",
    "prescriptionRequired": true,
    "manufacturer": "Sun Pharma",
    "imageUrl": "https://example.com/images/monteklc.jpg"
  },
  {
    "medicineName": "Taxim-O 200",
    "composition": "Cefixime (200mg)",
    "purpose": "Typhoid, Urinary Infections",
    "category": "Antibiotic",
    "dosageAdults": "1 tablet twice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Diarrhea, indigestion",
    "sideEffectsRare": "",
    "contraindications": "Cephalosporin allergy",
    "prescriptionRequired": true,
    "manufacturer": "Alkem Laboratories",
    "imageUrl": "https://example.com/images/taximo200.jpg"
  },
  {
    "medicineName": "Norflox 400",
    "composition": "Norfloxacin (400mg)",
    "purpose": "Stomach infection, Diarrhea",
    "category": "Antibiotic",
    "dosageAdults": "1 tablet twice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Metallic taste, headache",
    "sideEffectsRare": "",
    "contraindications": "Pregnancy, tendonitis history",
    "prescriptionRequired": true,
    "manufacturer": "Cipla Ltd",
    "imageUrl": "https://example.com/images/norflox400.jpg"
  },
  {
    "medicineName": "Ultracet",
    "composition": "Tramadol + Paracetamol",
    "purpose": "Severe pain relief",
    "category": "Painkiller",
    "dosageAdults": "Use only as prescribed (strictly)",
    "dosageChildren": "",
    "sideEffectsCommon": "Dizziness, sleepiness, constipation",
    "sideEffectsRare": "",
    "contraindications": "Respiratory depression, asthma",
    "prescriptionRequired": true,
    "manufacturer": "Janssen",
    "imageUrl": "https://example.com/images/ultracet.jpg"
  },
  {
    "medicineName": "Zerodol-P",
    "composition": "Aceclofenac + Paracetamol",
    "purpose": "Arthritis, joint pain",
    "category": "Anti-Inflammatory",
    "dosageAdults": "1 tablet twice daily after food",
    "dosageChildren": "",
    "sideEffectsCommon": "Gastric irritation",
    "sideEffectsRare": "",
    "contraindications": "Bleeding disorders, peptic ulcer",
    "prescriptionRequired": true,
    "manufacturer": "Ipca Laboratories",
    "imageUrl": "https://example.com/images/zerodolp.jpg"
  },
  {
    "medicineName": "Benadryl Syrup",
    "composition": "Diphenhydramine",
    "purpose": "Dry cough, allergy symptoms",
    "category": "Cough & Cold",
    "dosageAdults": "10ml every 4-6 hours",
    "dosageChildren": "",
    "sideEffectsCommon": "Marked drowsiness",
    "sideEffectsRare": "",
    "contraindications": "Glaucoma, driving",
    "prescriptionRequired": false,
    "manufacturer": "Johnson & Johnson",
    "imageUrl": "https://example.com/images/benadryl.jpg"
  },
  {
    "medicineName": "Otrivin Oxy",
    "composition": "Oxymetazoline",
    "purpose": "Nasal congestion (blocked nose)",
    "category": "Respiratory",
    "dosageAdults": "1-2 sprays in each nostril",
    "dosageChildren": "",
    "sideEffectsCommon": "Nasal dryness, sneezing",
    "sideEffectsRare": "",
    "contraindications": "High BP (consult doctor)",
    "prescriptionRequired": false,
    "manufacturer": "GSK",
    "imageUrl": "https://example.com/images/otrivin.jpg"
  },
  {
    "medicineName": "Candid Powder",
    "composition": "Clotrimazole (1%)",
    "purpose": "Fungal sweat rash, athlete's foot",
    "category": "Other",
    "dosageAdults": "Dust on affected area twice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Mild burning sensation",
    "sideEffectsRare": "",
    "contraindications": "None specifically",
    "prescriptionRequired": false,
    "manufacturer": "Glenmark Pharmaceuticals",
    "imageUrl": "https://example.com/images/candid.jpg"
  },
  {
    "medicineName": "Omnigel",
    "composition": "Diclofenac Gel",
    "purpose": "Muscle sprains, back pain",
    "category": "Anti-Inflammatory",
    "dosageAdults": "Apply 3-4 times daily on pain area",
    "dosageChildren": "",
    "sideEffectsCommon": "Skin rash (rare)",
    "sideEffectsRare": "",
    "contraindications": "Open wounds",
    "prescriptionRequired": false,
    "manufacturer": "Cipla Ltd",
    "imageUrl": "https://example.com/images/omnigel.jpg"
  },
  {
    "medicineName": "Revital H",
    "composition": "Multivitamins + Ginseng",
    "purpose": "Fatigue, weakness",
    "category": "Vitamin/Supplement",
    "dosageAdults": "1 capsule daily with breakfast",
    "dosageChildren": "",
    "sideEffectsCommon": "Nervousness (due to Ginseng)",
    "sideEffectsRare": "",
    "contraindications": "High blood pressure (consult doctor)",
    "prescriptionRequired": false,
    "manufacturer": "Sun Pharma",
    "imageUrl": "https://example.com/images/revital.jpg"
  },
  {
    "medicineName": "Evion 400",
    "composition": "Vitamin E (400mg)",
    "purpose": "Muscle cramps, skin health",
    "category": "Vitamin/Supplement",
    "dosageAdults": "1 capsule daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Headache, nausea (rare)",
    "sideEffectsRare": "",
    "contraindications": "Bleeding disorders",
    "prescriptionRequired": false,
    "manufacturer": "Merck",
    "imageUrl": "https://example.com/images/evion.jpg"
  },
  {
    "medicineName": "Udiliv 300",
    "composition": "Ursodeoxycholic Acid",
    "purpose": "Gallstones, Fatty liver",
    "category": "Gastrointestinal",
    "dosageAdults": "As prescribed by doctor",
    "dosageChildren": "",
    "sideEffectsCommon": "Loose motion",
    "sideEffectsRare": "",
    "contraindications": "Biliary obstruction",
    "prescriptionRequired": true,
    "manufacturer": "Abbott",
    "imageUrl": "https://example.com/images/udiliv.jpg"
  },
  {
    "medicineName": "Zincovit",
    "composition": "Multivitamin + Zinc",
    "purpose": "Immunity support",
    "category": "Vitamin/Supplement",
    "dosageAdults": "1 tablet daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Metallic taste",
    "sideEffectsRare": "",
    "contraindications": "None specifically",
    "prescriptionRequired": false,
    "manufacturer": "Apex Laboratories",
    "imageUrl": "https://example.com/images/zincovit.jpg"
  },
  {
    "medicineName": "Deriphyllin",
    "composition": "Etofylline + Theophylline",
    "purpose": "Asthma, COPD, Breathlessness",
    "category": "Respiratory",
    "dosageAdults": "1 tablet twice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Headache, palpitations",
    "sideEffectsRare": "",
    "contraindications": "Acute heart attack history",
    "prescriptionRequired": true,
    "manufacturer": "Zydus Cadila",
    "imageUrl": "https://example.com/images/deriphyllin.jpg"
  },
  {
    "medicineName": "Metrogyl 400",
    "composition": "Metronidazole (400mg)",
    "purpose": "Stomach infection, dysentery",
    "category": "Antibiotic",
    "dosageAdults": "1 tablet every 8 hours",
    "dosageChildren": "",
    "sideEffectsCommon": "Metallic taste, dark urine",
    "sideEffectsRare": "",
    "contraindications": "Alcohol consumption (Strictly No)",
    "prescriptionRequired": true,
    "manufacturer": "J.B. Chemicals",
    "imageUrl": "https://example.com/images/metrogyl.jpg"
  },
  {
    "medicineName": "Dytor 10",
    "composition": "Torsemide (10mg)",
    "purpose": "Edema (Water retention)",
    "category": "Cardiovascular",
    "dosageAdults": "1 tablet in morning (causes urination)",
    "dosageChildren": "",
    "sideEffectsCommon": "Dehydration, low potassium",
    "sideEffectsRare": "",
    "contraindications": "Anuria (kidney failure)",
    "prescriptionRequired": true,
    "manufacturer": "Cipla Ltd",
    "imageUrl": "https://example.com/images/dytor.jpg"
  },
  {
    "medicineName": "Ecosprin 75",
    "composition": "Aspirin (75mg)",
    "purpose": "Prevention of heart attack/stroke",
    "category": "Cardiovascular",
    "dosageAdults": "1 tablet daily with food",
    "dosageChildren": "",
    "sideEffectsCommon": "Increased bleeding time, gastritis",
    "sideEffectsRare": "",
    "contraindications": "Hemophilia, stomach ulcers",
    "prescriptionRequired": true,
    "manufacturer": "USV Pvt Ltd",
    "imageUrl": "https://example.com/images/ecosprin.jpg"
  },
  {
    "medicineName": "Avil 25",
    "composition": "Pheniramine Maleate",
    "purpose": "Severe allergic reactions",
    "category": "Antihistamine",
    "dosageAdults": "1 tablet when needed",
    "dosageChildren": "",
    "sideEffectsCommon": "Strong sedation (sleepiness)",
    "sideEffectsRare": "",
    "contraindications": "Prostate enlargement",
    "prescriptionRequired": false,
    "manufacturer": "Sanofi India",
    "imageUrl": "https://example.com/images/avil.jpg"
  },
  {
    "medicineName": "Febrex Plus",
    "composition": "Paracetamol + Phenylephrine + CPM",
    "purpose": "Flu, Fever, Body ache",
    "category": "Cough & Cold",
    "dosageAdults": "1 tablet thrice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Drowsiness, dry throat",
    "sideEffectsRare": "",
    "contraindications": "High BP",
    "prescriptionRequired": false,
    "manufacturer": "Indoco Remedies",
    "imageUrl": "https://example.com/images/febrex.jpg"
  },
  {
    "medicineName": "Digene Tablet",
    "composition": "Magnesium + Aluminium Hydroxide",
    "purpose": "Acidity, Heartburn",
    "category": "Antacid",
    "dosageAdults": "Chew 1-2 tablets after meals",
    "dosageChildren": "",
    "sideEffectsCommon": "Constipation",
    "sideEffectsRare": "",
    "contraindications": "Kidney stones",
    "prescriptionRequired": false,
    "manufacturer": "Abbott",
    "imageUrl": "https://example.com/images/digene.jpg"
  },
  {
    "medicineName": "Vertin 16",
    "composition": "Betahistine (16mg)",
    "purpose": "Vertigo (Dizziness)",
    "category": "Other",
    "dosageAdults": "1 tablet twice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Nausea, headache",
    "sideEffectsRare": "",
    "contraindications": "Pheochromocytoma",
    "prescriptionRequired": true,
    "manufacturer": "Abbott",
    "imageUrl": "https://example.com/images/vertin.jpg"
  },
  {
    "medicineName": "Stemetil",
    "composition": "Prochlorperazine",
    "purpose": "Nausea, Vomiting, Migraine",
    "category": "Gastrointestinal",
    "dosageAdults": "1 tablet when nauseous",
    "dosageChildren": "",
    "sideEffectsCommon": "Drowsiness",
    "sideEffectsRare": "",
    "contraindications": "Parkinson's disease",
    "prescriptionRequired": true,
    "manufacturer": "Abbott",
    "imageUrl": "https://example.com/images/stemetil.jpg"
  },
  {
    "medicineName": "Neurobion Forte",
    "composition": "Vitamin B1 + B6 + B12",
    "purpose": "Nerve health",
    "category": "Vitamin/Supplement",
    "dosageAdults": "1 tablet daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Excess urination",
    "sideEffectsRare": "",
    "contraindications": "None specifically",
    "prescriptionRequired": false,
    "manufacturer": "P&G Health",
    "imageUrl": "https://example.com/images/neurobion.jpg"
  },
  {
    "medicineName": "Mucaine Gel",
    "composition": "Oxetacaine + Aluminium + Magnesium",
    "purpose": "Stomach ulcers, burning sensation",
    "category": "Antacid",
    "dosageAdults": "10ml before meals",
    "dosageChildren": "",
    "sideEffectsCommon": "Constipation",
    "sideEffectsRare": "",
    "contraindications": "Kidney dysfunction",
    "prescriptionRequired": true,
    "manufacturer": "Pfizer Ltd",
    "imageUrl": "https://example.com/images/mucaine.jpg"
  },
  {
    "medicineName": "Zentel",
    "composition": "Albendazole (400mg)",
    "purpose": "Worm infection",
    "category": "Other",
    "dosageAdults": "1 tablet single dose (chew)",
    "dosageChildren": "",
    "sideEffectsCommon": "Stomach pain",
    "sideEffectsRare": "",
    "contraindications": "Pregnancy",
    "prescriptionRequired": true,
    "manufacturer": "GSK",
    "imageUrl": "https://example.com/images/zentel.jpg"
  },
  {
    "medicineName": "T-Bact",
    "composition": "Mupirocin Ointment",
    "purpose": "Skin bacterial infection",
    "category": "Antibiotic",
    "dosageAdults": "Apply on infected skin 3 times daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Itching at site",
    "sideEffectsRare": "",
    "contraindications": "Large open wounds",
    "prescriptionRequired": true,
    "manufacturer": "GSK",
    "imageUrl": "https://example.com/images/tbact.jpg"
  },
  {
    "medicineName": "Dulcoflex",
    "composition": "Bisacodyl (5mg)",
    "purpose": "Constipation relief",
    "category": "Gastrointestinal",
    "dosageAdults": "1 tablet at bedtime",
    "dosageChildren": "",
    "sideEffectsCommon": "Stomach cramps",
    "sideEffectsRare": "",
    "contraindications": "Appendicitis, intestinal obstruction",
    "prescriptionRequired": false,
    "manufacturer": "Sanofi India",
    "imageUrl": "https://example.com/images/dulcoflex.jpg"
  },
  {
    "medicineName": "Calpol 500",
    "composition": "Paracetamol (500mg)",
    "purpose": "Fever, mild pain",
    "category": "Painkiller",
    "dosageAdults": "1 tablet every 4-6 hours",
    "dosageChildren": "",
    "sideEffectsCommon": "Nausea (rare)",
    "sideEffectsRare": "",
    "contraindications": "Liver failure",
    "prescriptionRequired": false,
    "manufacturer": "GSK",
    "imageUrl": "https://example.com/images/calpol500.jpg"
  },
  {
    "medicineName": "Rantac 150",
    "composition": "Ranitidine (150mg)",
    "purpose": "Acidity, Gastritis",
    "category": "Antacid",
    "dosageAdults": "1 tablet twice daily before food",
    "dosageChildren": "",
    "sideEffectsCommon": "Headache, fatigue",
    "sideEffectsRare": "",
    "contraindications": "Porphyria",
    "prescriptionRequired": false,
    "manufacturer": "J.B. Chemicals",
    "imageUrl": "https://example.com/images/rantac150.jpg"
  },
  {
    "medicineName": "Volini Spray",
    "composition": "Diclofenac + Menthol",
    "purpose": "Joint pain, sprains",
    "category": "Anti-Inflammatory",
    "dosageAdults": "Spray on affected area 3-4 times daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Skin irritation",
    "sideEffectsRare": "",
    "contraindications": "Open wounds",
    "prescriptionRequired": false,
    "manufacturer": "Sun Pharma",
    "imageUrl": "https://example.com/images/volini.jpg"
  },
  {
    "medicineName": "Asthalin Inhaler",
    "composition": "Salbutamol (100mcg)",
    "purpose": "Asthma attack, Breathlessness",
    "category": "Respiratory",
    "dosageAdults": "2 puffs when needed",
    "dosageChildren": "",
    "sideEffectsCommon": "Shaking hands, fast heartbeat",
    "sideEffectsRare": "",
    "contraindications": "Severe heart disease",
    "prescriptionRequired": true,
    "manufacturer": "Cipla Ltd",
    "imageUrl": "https://example.com/images/asthalin.jpg"
  },
  {
    "medicineName": "Gemer 2",
    "composition": "Glimepiride (2mg) + Metformin",
    "purpose": "Diabetes management",
    "category": "Antidiabetic",
    "dosageAdults": "1 tablet before breakfast",
    "dosageChildren": "",
    "sideEffectsCommon": "Low blood sugar, nausea",
    "sideEffectsRare": "",
    "contraindications": "Kidney disease",
    "prescriptionRequired": true,
    "manufacturer": "Sun Pharma",
    "imageUrl": "https://example.com/images/gemer2.jpg"
  },
  {
    "medicineName": "Soframycin Cream",
    "composition": "Framycetin Sulfate",
    "purpose": "Skin infections, minor burns",
    "category": "Antibiotic",
    "dosageAdults": "Apply twice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Itching, redness",
    "sideEffectsRare": "",
    "contraindications": "Large open wounds",
    "prescriptionRequired": false,
    "manufacturer": "Sanofi India",
    "imageUrl": "https://example.com/images/soframycin.jpg"
  },
  {
    "medicineName": "Corex DX",
    "composition": "Dextromethorphan + CPM",
    "purpose": "Dry cough",
    "category": "Cough & Cold",
    "dosageAdults": "5ml thrice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Drowsiness, dizziness",
    "sideEffectsRare": "",
    "contraindications": "Asthma, respiratory failure",
    "prescriptionRequired": false,
    "manufacturer": "Pfizer Ltd",
    "imageUrl": "https://example.com/images/corexdx.jpg"
  },
  {
    "medicineName": "Thyronorm 25",
    "composition": "Thyroxine Sodium (25mcg)",
    "purpose": "Hypothyroidism",
    "category": "Other",
    "dosageAdults": "1 tablet empty stomach morning",
    "dosageChildren": "",
    "sideEffectsCommon": "Palpitations (if dose high)",
    "sideEffectsRare": "",
    "contraindications": "Heart attack history",
    "prescriptionRequired": true,
    "manufacturer": "Abbott",
    "imageUrl": "https://example.com/images/thyronorm.jpg"
  },
  {
    "medicineName": "Pan-D",
    "composition": "Pantoprazole + Domperidone",
    "purpose": "Acidity with nausea",
    "category": "Antacid",
    "dosageAdults": "1 capsule empty stomach",
    "dosageChildren": "",
    "sideEffectsCommon": "Dry mouth, headache",
    "sideEffectsRare": "",
    "contraindications": "Intestinal blockage",
    "prescriptionRequired": true,
    "manufacturer": "Alkem Laboratories",
    "imageUrl": "https://example.com/images/pand.jpg"
  },
  {
    "medicineName": "Clavam 625",
    "composition": "Amoxicillin + Clavulanic Acid",
    "purpose": "Severe bacterial infections",
    "category": "Antibiotic",
    "dosageAdults": "1 tablet twice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Diarrhea, yeast infection",
    "sideEffectsRare": "",
    "contraindications": "Penicillin allergy",
    "prescriptionRequired": true,
    "manufacturer": "Alkem Laboratories",
    "imageUrl": "https://example.com/images/clavam.jpg"
  },
  {
    "medicineName": "Nise Tablet",
    "composition": "Nimesulide (100mg)",
    "purpose": "Acute pain, fever",
    "category": "Anti-Inflammatory",
    "dosageAdults": "1 tablet after food",
    "dosageChildren": "",
    "sideEffectsCommon": "Liver toxicity (if overused)",
    "sideEffectsRare": "",
    "contraindications": "Liver disease, kids under 12",
    "prescriptionRequired": true,
    "manufacturer": "Dr. Reddy's",
    "imageUrl": "https://example.com/images/nise.jpg"
  },
  {
    "medicineName": "Rosuvas 10",
    "composition": "Rosuvastatin (10mg)",
    "purpose": "High Cholesterol",
    "category": "Cardiovascular",
    "dosageAdults": "1 tablet at night",
    "dosageChildren": "",
    "sideEffectsCommon": "Muscle pain, weakness",
    "sideEffectsRare": "",
    "contraindications": "Active liver disease",
    "prescriptionRequired": true,
    "manufacturer": "Sun Pharma",
    "imageUrl": "https://example.com/images/rosuvas.jpg"
  },
  {
    "medicineName": "Cremaffin",
    "composition": "Liquid Paraffin + Milk of Magnesia",
    "purpose": "Constipation",
    "category": "Gastrointestinal",
    "dosageAdults": "1-2 spoons at bedtime",
    "dosageChildren": "",
    "sideEffectsCommon": "Stomach cramps",
    "sideEffectsRare": "",
    "contraindications": "Appendicitis",
    "prescriptionRequired": false,
    "manufacturer": "Abbott",
    "imageUrl": "https://example.com/images/cremaffin.jpg"
  },
  {
    "medicineName": "Concor 5",
    "composition": "Bisoprolol (5mg)",
    "purpose": "Hypertension, Heart rate control",
    "category": "Cardiovascular",
    "dosageAdults": "1 tablet daily morning",
    "dosageChildren": "",
    "sideEffectsCommon": "Slow heart rate, fatigue",
    "sideEffectsRare": "",
    "contraindications": "Asthma, severe low BP",
    "prescriptionRequired": true,
    "manufacturer": "Merck",
    "imageUrl": "https://example.com/images/concor.jpg"
  },
  {
    "medicineName": "Budecort Respules",
    "composition": "Budesonide (0.5mg)",
    "purpose": "Asthma (Nebulization)",
    "category": "Respiratory",
    "dosageAdults": "As per doctor instruction",
    "dosageChildren": "",
    "sideEffectsCommon": "Throat irritation",
    "sideEffectsRare": "",
    "contraindications": "Tuberculosis",
    "prescriptionRequired": true,
    "manufacturer": "Cipla Ltd",
    "imageUrl": "https://example.com/images/budecort.jpg"
  },
  {
    "medicineName": "Cheston Cold",
    "composition": "Cetirizine + Paracetamol + Phenylephrine",
    "purpose": "Cold and Flu",
    "category": "Cough & Cold",
    "dosageAdults": "1 tablet thrice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Drowsiness",
    "sideEffectsRare": "",
    "contraindications": "High blood pressure",
    "prescriptionRequired": false,
    "manufacturer": "Cipla Ltd",
    "imageUrl": "https://example.com/images/cheston.jpg"
  },
  {
    "medicineName": "Ostocalcium",
    "composition": "Calcium + Vitamin D3",
    "purpose": "Bone health (kids/adults)",
    "category": "Vitamin/Supplement",
    "dosageAdults": "1-2 tablets chewable daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Constipation (rare)",
    "sideEffectsRare": "",
    "contraindications": "Hypercalcemia",
    "prescriptionRequired": false,
    "manufacturer": "GSK",
    "imageUrl": "https://example.com/images/ostocalcium.jpg"
  },
  {
    "medicineName": "Dexorange Syrup",
    "composition": "Iron + Folic Acid + Vit B12",
    "purpose": "Anemia (Low blood)",
    "category": "Vitamin/Supplement",
    "dosageAdults": "1 tablespoon twice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Black stool, metallic taste",
    "sideEffectsRare": "",
    "contraindications": "Iron overload",
    "prescriptionRequired": false,
    "manufacturer": "Franco-Indian",
    "imageUrl": "https://example.com/images/dexorange.jpg"
  },
  {
    "medicineName": "Betnesol 0.5",
    "composition": "Betamethasone (0.5mg)",
    "purpose": "Severe allergy, inflammation",
    "category": "Other",
    "dosageAdults": "Short term use only (as prescribed)",
    "dosageChildren": "",
    "sideEffectsCommon": "Weight gain, mood swings",
    "sideEffectsRare": "",
    "contraindications": "Untreated infections",
    "prescriptionRequired": true,
    "manufacturer": "GSK",
    "imageUrl": "https://example.com/images/betnesol.jpg"
  },
  {
    "medicineName": "Chymoral Forte",
    "composition": "Trypsin Chymotrypsin",
    "purpose": "Swelling, wound healing",
    "category": "Other",
    "dosageAdults": "1 tablet 3 times daily before food",
    "dosageChildren": "",
    "sideEffectsCommon": "Allergic reaction (rare)",
    "sideEffectsRare": "",
    "contraindications": "Blood clotting disorders",
    "prescriptionRequired": true,
    "manufacturer": "Torrent Pharma",
    "imageUrl": "https://example.com/images/chymoral.jpg"
  },
  {
    "medicineName": "Envas 5",
    "composition": "Enalapril (5mg)",
    "purpose": "High BP, Heart failure",
    "category": "Cardiovascular",
    "dosageAdults": "1 tablet daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Dry cough",
    "sideEffectsRare": "",
    "contraindications": "Pregnancy",
    "prescriptionRequired": true,
    "manufacturer": "Cadila",
    "imageUrl": "https://example.com/images/envas.jpg"
  },
  {
    "medicineName": "Grisovin FP",
    "composition": "Griseofulvin (250mg)",
    "purpose": "Fungal infection (Ringworm)",
    "category": "Other",
    "dosageAdults": "1 tablet daily with fatty meal",
    "dosageChildren": "",
    "sideEffectsCommon": "Nausea, headache",
    "sideEffectsRare": "",
    "contraindications": "Liver failure, Pregnancy",
    "prescriptionRequired": true,
    "manufacturer": "GSK",
    "imageUrl": "https://example.com/images/grisovin.jpg"
  },
  {
    "medicineName": "Duolin Respules",
    "composition": "Levosalbutamol + Ipratropium",
    "purpose": "COPD, Severe Asthma",
    "category": "Respiratory",
    "dosageAdults": "Nebulize as needed",
    "dosageChildren": "",
    "sideEffectsCommon": "Dry mouth, palpitations",
    "sideEffectsRare": "",
    "contraindications": "Glaucoma",
    "prescriptionRequired": true,
    "manufacturer": "Cipla Ltd",
    "imageUrl": "https://example.com/images/duolin.jpg"
  },
  {
    "medicineName": "Liv-52",
    "composition": "Herbal extracts",
    "purpose": "Liver health, appetite",
    "category": "Other",
    "dosageAdults": "2 tablets twice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "None reported usually",
    "sideEffectsRare": "",
    "contraindications": "None specifically",
    "prescriptionRequired": false,
    "manufacturer": "Himalaya",
    "imageUrl": "https://example.com/images/liv52.jpg"
  },
  {
    "medicineName": "Sporidex 500",
    "composition": "Cephalexin (500mg)",
    "purpose": "Skin/Bone bacterial infection",
    "category": "Antibiotic",
    "dosageAdults": "1 capsule every 6 hours",
    "dosageChildren": "",
    "sideEffectsCommon": "Diarrhea",
    "sideEffectsRare": "",
    "contraindications": "Cephalosporin allergy",
    "prescriptionRequired": true,
    "manufacturer": "Sun Pharma",
    "imageUrl": "https://example.com/images/sporidex.jpg"
  },
  {
    "medicineName": "Brufen 400",
    "composition": "Ibuprofen (400mg)",
    "purpose": "Pain, Swelling",
    "category": "Anti-Inflammatory",
    "dosageAdults": "1 tablet after food",
    "dosageChildren": "",
    "sideEffectsCommon": "Acidity, stomach burn",
    "sideEffectsRare": "",
    "contraindications": "Stomach ulcers",
    "prescriptionRequired": false,
    "manufacturer": "Abbott",
    "imageUrl": "https://example.com/images/brufen.jpg"
  },
  {
    "medicineName": "I-Pill",
    "composition": "Levonorgestrel (1.5mg)",
    "purpose": "Emergency Contraception",
    "category": "Other",
    "dosageAdults": "1 tablet within 72 hours of unprotected sex",
    "dosageChildren": "",
    "sideEffectsCommon": "Nausea, delayed period",
    "sideEffectsRare": "",
    "contraindications": "Pregnancy (already established)",
    "prescriptionRequired": false,
    "manufacturer": "Piramal",
    "imageUrl": "https://example.com/images/ipill.jpg"
  },
  {
    "medicineName": "Wysolone 5",
    "composition": "Prednisolone (5mg)",
    "purpose": "Autoimmune disease, allergy",
    "category": "Other",
    "dosageAdults": "As per strict prescription",
    "dosageChildren": "",
    "sideEffectsCommon": "Bone thinning, immunity drop",
    "sideEffectsRare": "",
    "contraindications": "Fungal infections",
    "prescriptionRequired": true,
    "manufacturer": "Pfizer Ltd",
    "imageUrl": "https://example.com/images/wysolone.jpg"
  },
  {
    "medicineName": "Nasivion Adult",
    "composition": "Oxymetazoline",
    "purpose": "Blocked nose",
    "category": "Respiratory",
    "dosageAdults": "2 drops twice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Rebound congestion (if used >5 days)",
    "sideEffectsRare": "",
    "contraindications": "High BP",
    "prescriptionRequired": false,
    "manufacturer": "Merck",
    "imageUrl": "https://example.com/images/nasivion.jpg"
  },
  {
    "medicineName": "Vicks Action 500",
    "composition": "Paracetamol + Diphenhydramine + Caffeine",
    "purpose": "Cold, Headache",
    "category": "Cough & Cold",
    "dosageAdults": "1 tablet every 6 hours",
    "dosageChildren": "",
    "sideEffectsCommon": "Drowsiness",
    "sideEffectsRare": "",
    "contraindications": "High BP",
    "prescriptionRequired": false,
    "manufacturer": "P&G",
    "imageUrl": "https://example.com/images/vicks.jpg"
  },
  {
    "medicineName": "Cyclopam",
    "composition": "Dicyclomine + Paracetamol",
    "purpose": "Stomach pain, cramps",
    "category": "Gastrointestinal",
    "dosageAdults": "1 tablet when needed",
    "dosageChildren": "",
    "sideEffectsCommon": "Dry mouth, blurred vision",
    "sideEffectsRare": "",
    "contraindications": "Glaucoma",
    "prescriptionRequired": false,
    "manufacturer": "Indoco Remedies",
    "imageUrl": "https://example.com/images/cyclopam.jpg"
  },
  {
    "medicineName": "Cipladine Ointment",
    "composition": "Povidone Iodine (5%)",
    "purpose": "Wounds, Cuts",
    "category": "Other",
    "dosageAdults": "Apply on wound",
    "dosageChildren": "",
    "sideEffectsCommon": "Staining of skin",
    "sideEffectsRare": "",
    "contraindications": "Thyroid issues",
    "prescriptionRequired": false,
    "manufacturer": "Cipla Ltd",
    "imageUrl": "https://example.com/images/cipladine.jpg"
  },
  {
    "medicineName": "Grilinctus BM",
    "composition": "Terbutaline + Bromhexine",
    "purpose": "Productive Cough",
    "category": "Cough & Cold",
    "dosageAdults": "10ml thrice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Hand tremors",
    "sideEffectsRare": "",
    "contraindications": "Heart palpitations",
    "prescriptionRequired": true,
    "manufacturer": "Franco-Indian",
    "imageUrl": "https://example.com/images/grilinctus.jpg"
  },
  {
    "medicineName": "Orofer XT",
    "composition": "Ferrous Ascorbate + Folic Acid",
    "purpose": "Iron deficiency anemia",
    "category": "Vitamin/Supplement",
    "dosageAdults": "1 tablet after lunch",
    "dosageChildren": "",
    "sideEffectsCommon": "Dark stool, constipation",
    "sideEffectsRare": "",
    "contraindications": "Thalassemia",
    "prescriptionRequired": false,
    "manufacturer": "Emcure",
    "imageUrl": "https://example.com/images/orofer.jpg"
  },
  {
    "medicineName": "Sorbitrate 5",
    "composition": "Isosorbide Dinitrate",
    "purpose": "Angina (Chest pain)",
    "category": "Cardiovascular",
    "dosageAdults": "Place under tongue during pain",
    "dosageChildren": "",
    "sideEffectsCommon": "Severe headache, low BP",
    "sideEffectsRare": "",
    "contraindications": "Viagra usage (Fatal drop in BP)",
    "prescriptionRequired": true,
    "manufacturer": "Abbott",
    "imageUrl": "https://example.com/images/sorbitrate.jpg"
  },
  {
    "medicineName": "Azithral Liquid",
    "composition": "Azithromycin (200mg/5ml)",
    "purpose": "Throat infection in kids",
    "category": "Antibiotic",
    "dosageAdults": "As per weight (doctor prescribed)",
    "dosageChildren": "",
    "sideEffectsCommon": "Vomiting, stomach pain",
    "sideEffectsRare": "",
    "contraindications": "Liver issues",
    "prescriptionRequired": true,
    "manufacturer": "Alembic",
    "imageUrl": "https://example.com/images/azithral_liq.jpg"
  },
  {
    "medicineName": "Manforce 100",
    "composition": "Sildenafil Citrate",
    "purpose": "Erectile Dysfunction",
    "category": "Other",
    "dosageAdults": "1 tablet 1 hour before activity",
    "dosageChildren": "",
    "sideEffectsCommon": "Headache, flushing, vision blue tint",
    "sideEffectsRare": "",
    "contraindications": "Heart patients on Nitrates",
    "prescriptionRequired": true,
    "manufacturer": "Mankind",
    "imageUrl": "https://example.com/images/manforce.jpg"
  },
  {
    "medicineName": "Plavix 75",
    "composition": "Clopidogrel (75mg)",
    "purpose": "Prevent blood clots",
    "category": "Cardiovascular",
    "dosageAdults": "1 tablet daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Easy bruising, bleeding",
    "sideEffectsRare": "",
    "contraindications": "Active bleeding (ulcer)",
    "prescriptionRequired": true,
    "manufacturer": "Sanofi",
    "imageUrl": "https://example.com/images/plavix.jpg"
  },
  {
    "medicineName": "Lasix 40",
    "composition": "Furosemide (40mg)",
    "purpose": "Fluid retention, high BP",
    "category": "Cardiovascular",
    "dosageAdults": "1 tablet morning",
    "dosageChildren": "",
    "sideEffectsCommon": "Dehydration, weakness",
    "sideEffectsRare": "",
    "contraindications": "Anuria",
    "prescriptionRequired": true,
    "manufacturer": "Sanofi",
    "imageUrl": "https://example.com/images/lasix.jpg"
  },
  {
    "medicineName": "Ketorol DT",
    "composition": "Ketorolac (10mg)",
    "purpose": "Severe toothache, post-op pain",
    "category": "Painkiller",
    "dosageAdults": "1 tablet (dissolve in water) when needed",
    "dosageChildren": "",
    "sideEffectsCommon": "Stomach pain",
    "sideEffectsRare": "",
    "contraindications": "Kidney failure, bleeding risk",
    "prescriptionRequired": true,
    "manufacturer": "Dr. Reddy's",
    "imageUrl": "https://example.com/images/ketorol.jpg"
  },
  {
    "medicineName": "Permite Cream",
    "composition": "Permethrin (5%)",
    "purpose": "Scabies, Lice",
    "category": "Other",
    "dosageAdults": "Apply neck down, wash after 8 hrs",
    "dosageChildren": "",
    "sideEffectsCommon": "Burning sensation",
    "sideEffectsRare": "",
    "contraindications": "Use on broken skin",
    "prescriptionRequired": true,
    "manufacturer": "Encube Ethicals",
    "imageUrl": "https://example.com/images/permite.jpg"
  },
  {
    "medicineName": "Aciloc 150",
    "composition": "Ranitidine (150mg)",
    "purpose": "Acidity",
    "category": "Antacid",
    "dosageAdults": "1 tablet twice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Headache",
    "sideEffectsRare": "",
    "contraindications": "Porphyria",
    "prescriptionRequired": false,
    "manufacturer": "Cadila",
    "imageUrl": "https://example.com/images/aciloc.jpg"
  },
  {
    "medicineName": "Unienzyme",
    "composition": "Fungal Diastase + Charcoal",
    "purpose": "Indigestion, Gas",
    "category": "Gastrointestinal",
    "dosageAdults": "1 tablet after meals",
    "dosageChildren": "",
    "sideEffectsCommon": "Black stool",
    "sideEffectsRare": "",
    "contraindications": "None specifically",
    "prescriptionRequired": false,
    "manufacturer": "Unichem",
    "imageUrl": "https://example.com/images/unienzyme.jpg"
  },
  {
    "medicineName": "Azee 500",
    "composition": "Azithromycin (500mg)",
    "purpose": "Throat/Chest infection",
    "category": "Antibiotic",
    "dosageAdults": "1 tablet daily for 3 days",
    "dosageChildren": "",
    "sideEffectsCommon": "Stomach cramps",
    "sideEffectsRare": "",
    "contraindications": "Liver disease",
    "prescriptionRequired": true,
    "manufacturer": "Cipla Ltd",
    "imageUrl": "https://example.com/images/azee.jpg"
  },
  {
    "medicineName": "Febutaz 40",
    "composition": "Febuxostat (40mg)",
    "purpose": "High Uric Acid (Gout)",
    "category": "Other",
    "dosageAdults": "1 tablet daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Liver enzyme changes",
    "sideEffectsRare": "",
    "contraindications": "Ischemic heart disease",
    "prescriptionRequired": true,
    "manufacturer": "Sun Pharma",
    "imageUrl": "https://example.com/images/febutaz.jpg"
  },
  {
    "medicineName": "Drotin-M",
    "composition": "Drotaverine + Mefenamic Acid",
    "purpose": "Stomach pain, period pain",
    "category": "Painkiller",
    "dosageAdults": "1 tablet when needed",
    "dosageChildren": "",
    "sideEffectsCommon": "Dry mouth",
    "sideEffectsRare": "",
    "contraindications": "Low BP",
    "prescriptionRequired": true,
    "manufacturer": "Walter Bushnell",
    "imageUrl": "https://example.com/images/drotinm.jpg"
  },
  {
    "medicineName": "Normaxin",
    "composition": "Clidinium + Chlordiazepoxide + Dicyclomine",
    "purpose": "IBS, Stomach cramps due to anxiety",
    "category": "Gastrointestinal",
    "dosageAdults": "1 tablet before meals",
    "dosageChildren": "",
    "sideEffectsCommon": "Drowsiness, confusion",
    "sideEffectsRare": "",
    "contraindications": "Glaucoma",
    "prescriptionRequired": true,
    "manufacturer": "Systopic",
    "imageUrl": "https://example.com/images/normaxin.jpg"
  },
  {
    "medicineName": "Saridon",
    "composition": "Paracetamol + Propyphenazone + Caffeine",
    "purpose": "Headache",
    "category": "Painkiller",
    "dosageAdults": "1 tablet when needed",
    "dosageChildren": "",
    "sideEffectsCommon": "Skin rash (rare)",
    "sideEffectsRare": "",
    "contraindications": "G6PD deficiency",
    "prescriptionRequired": false,
    "manufacturer": "Piramal",
    "imageUrl": "https://example.com/images/saridon.jpg"
  },
  {
    "medicineName": "Mintop 5",
    "composition": "Minoxidil (5%)",
    "purpose": "Hair loss (Alopecia)",
    "category": "Other",
    "dosageAdults": "1ml on scalp twice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Scalp irritation",
    "sideEffectsRare": "",
    "contraindications": "Scalp infection",
    "prescriptionRequired": false,
    "manufacturer": "Dr. Reddy's",
    "imageUrl": "https://example.com/images/mintop.jpg"
  },
  {
    "medicineName": "Mederma Gel",
    "composition": "Allium Cepa extract",
    "purpose": "Scar removal",
    "category": "Other",
    "dosageAdults": "Apply on scar twice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Itching",
    "sideEffectsRare": "",
    "contraindications": "Open wounds",
    "prescriptionRequired": false,
    "manufacturer": "Merz Pharma",
    "imageUrl": "https://example.com/images/mederma.jpg"
  },
  {
    "medicineName": "Crocin Advance",
    "composition": "Paracetamol (500mg)",
    "purpose": "Fever, Headache",
    "category": "Painkiller",
    "dosageAdults": "1 tablet every 4-6 hours",
    "dosageChildren": "",
    "sideEffectsCommon": "Liver strain (if overdosed)",
    "sideEffectsRare": "",
    "contraindications": "Liver cirrhosis",
    "prescriptionRequired": false,
    "manufacturer": "GSK",
    "imageUrl": "https://example.com/images/crocin.jpg"
  },
  {
    "medicineName": "O2 Tablet",
    "composition": "Ofloxacin + Ornidazole",
    "purpose": "Diarrhea, Dysentery",
    "category": "Antibiotic",
    "dosageAdults": "1 tablet twice daily for 5 days",
    "dosageChildren": "",
    "sideEffectsCommon": "Nausea, metallic taste",
    "sideEffectsRare": "",
    "contraindications": "Epilepsy",
    "prescriptionRequired": true,
    "manufacturer": "Medley Pharmaceuticals",
    "imageUrl": "https://example.com/images/o2tablet.jpg"
  },
  {
    "medicineName": "Atarax 25",
    "composition": "Hydroxyzine (25mg)",
    "purpose": "Anxiety, Skin itching",
    "category": "Antihistamine",
    "dosageAdults": "1 tablet at night",
    "dosageChildren": "",
    "sideEffectsCommon": "Extreme drowsiness",
    "sideEffectsRare": "",
    "contraindications": "Early pregnancy",
    "prescriptionRequired": true,
    "manufacturer": "Dr. Reddy's",
    "imageUrl": "https://example.com/images/atarax.jpg"
  },
  {
    "medicineName": "Glyciphage 500",
    "composition": "Metformin (500mg)",
    "purpose": "Type 2 Diabetes",
    "category": "Antidiabetic",
    "dosageAdults": "1 tablet with meals",
    "dosageChildren": "",
    "sideEffectsCommon": "Stomach upset, gas",
    "sideEffectsRare": "",
    "contraindications": "Severe kidney disease",
    "prescriptionRequired": true,
    "manufacturer": "Franco-Indian",
    "imageUrl": "https://example.com/images/glyciphage.jpg"
  },
  {
    "medicineName": "Polybion LC",
    "composition": "B-Complex + Lysine",
    "purpose": "Appetite stimulation in kids",
    "category": "Vitamin/Supplement",
    "dosageAdults": "5ml twice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "None usually",
    "sideEffectsRare": "",
    "contraindications": "None specifically",
    "prescriptionRequired": false,
    "manufacturer": "P&G Health",
    "imageUrl": "https://example.com/images/polybion.jpg"
  },
  {
    "medicineName": "Ciplox Eye Drops",
    "composition": "Ciprofloxacin (0.3%)",
    "purpose": "Eye bacterial infection",
    "category": "Other",
    "dosageAdults": "1-2 drops every 4 hours",
    "dosageChildren": "",
    "sideEffectsCommon": "Eye stinging",
    "sideEffectsRare": "",
    "contraindications": "Viral eye infection",
    "prescriptionRequired": true,
    "manufacturer": "Cipla Ltd",
    "imageUrl": "https://example.com/images/ciplox_eye.jpg"
  },
  {
    "medicineName": "Refresh Tears",
    "composition": "Carboxymethylcellulose (0.5%)",
    "purpose": "Dry eyes",
    "category": "Other",
    "dosageAdults": "1-2 drops as needed",
    "dosageChildren": "",
    "sideEffectsCommon": "Blurry vision (temporary)",
    "sideEffectsRare": "",
    "contraindications": "Eye infection",
    "prescriptionRequired": false,
    "manufacturer": "Allergan",
    "imageUrl": "https://example.com/images/refresh.jpg"
  },
  {
    "medicineName": "Trapic 500",
    "composition": "Tranexamic Acid (500mg)",
    "purpose": "Stop heavy bleeding (Periods/Nose)",
    "category": "Other",
    "dosageAdults": "1 tablet thrice daily for 3 days",
    "dosageChildren": "",
    "sideEffectsCommon": "Nausea, leg pain",
    "sideEffectsRare": "",
    "contraindications": "Color blindness history",
    "prescriptionRequired": true,
    "manufacturer": "Sun Pharma",
    "imageUrl": "https://example.com/images/trapic.jpg"
  },
  {
    "medicineName": "Wikoryl",
    "composition": "Paracetamol + Phenylephrine + CPM",
    "purpose": "Fever, Cold, Blocked nose",
    "category": "Cough & Cold",
    "dosageAdults": "1 tablet thrice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Drowsiness",
    "sideEffectsRare": "",
    "contraindications": "Hypertension",
    "prescriptionRequired": false,
    "manufacturer": "Alembic",
    "imageUrl": "https://example.com/images/wikoryl.jpg"
  },
  {
    "medicineName": "Zyloric 100",
    "composition": "Allopurinol (100mg)",
    "purpose": "Gout (Uric acid reduction)",
    "category": "Other",
    "dosageAdults": "1 tablet daily after food",
    "dosageChildren": "",
    "sideEffectsCommon": "Skin rash",
    "sideEffectsRare": "",
    "contraindications": "Acute gout attack (wait till it settles)",
    "prescriptionRequired": true,
    "manufacturer": "GSK",
    "imageUrl": "https://example.com/images/zyloric.jpg"
  },
  {
    "medicineName": "Mucolite Syrup",
    "composition": "Ambroxol (30mg/5ml)",
    "purpose": "Chesty cough (Phlegm)",
    "category": "Cough & Cold",
    "dosageAdults": "10ml thrice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Gastric discomfort",
    "sideEffectsRare": "",
    "contraindications": "Gastric ulcer",
    "prescriptionRequired": false,
    "manufacturer": "Dr. Reddy's",
    "imageUrl": "https://example.com/images/mucolite.jpg"
  },
  {
    "medicineName": "Neosporin Powder",
    "composition": "Polymyxin B + Bacitracin",
    "purpose": "Prevent wound infection",
    "category": "Antibiotic",
    "dosageAdults": "Dust on wound twice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Itching",
    "sideEffectsRare": "",
    "contraindications": "Deep puncture wounds",
    "prescriptionRequired": false,
    "manufacturer": "GSK",
    "imageUrl": "https://example.com/images/neosporin.jpg"
  },
  {
    "medicineName": "Burnol",
    "composition": "Aminacrine + Cetrimide",
    "purpose": "Minor burns",
    "category": "Other",
    "dosageAdults": "Apply immediately on burn",
    "dosageChildren": "",
    "sideEffectsCommon": "Staining",
    "sideEffectsRare": "",
    "contraindications": "3rd degree burns",
    "prescriptionRequired": false,
    "manufacturer": "Morepen",
    "imageUrl": "https://example.com/images/burnol.jpg"
  },
  {
    "medicineName": "Urimax 0.4",
    "composition": "Tamsulosin (0.4mg)",
    "purpose": "Enlarged Prostate (BPH)",
    "category": "Other",
    "dosageAdults": "1 capsule after dinner",
    "dosageChildren": "",
    "sideEffectsCommon": "Dizziness upon standing",
    "sideEffectsRare": "",
    "contraindications": "Severe liver failure",
    "prescriptionRequired": true,
    "manufacturer": "Cipla Ltd",
    "imageUrl": "https://example.com/images/urimax.jpg"
  },
  {
    "medicineName": "Regestrone 5",
    "composition": "Norethisterone (5mg)",
    "purpose": "Delay periods, irregular periods",
    "category": "Other",
    "dosageAdults": "1 tablet twice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Headache, bloating",
    "sideEffectsRare": "",
    "contraindications": "Pregnancy, Breast cancer history",
    "prescriptionRequired": true,
    "manufacturer": "Novartis",
    "imageUrl": "https://example.com/images/regestrone.jpg"
  },
  {
    "medicineName": "Flexon",
    "composition": "Ibuprofen + Paracetamol",
    "purpose": "Body pain, fever",
    "category": "Painkiller",
    "dosageAdults": "1 tablet after food",
    "dosageChildren": "",
    "sideEffectsCommon": "Acidity",
    "sideEffectsRare": "",
    "contraindications": "Stomach ulcers",
    "prescriptionRequired": false,
    "manufacturer": "Aristo",
    "imageUrl": "https://example.com/images/flexon.jpg"
  },
  {
    "medicineName": "Gudcef 200",
    "composition": "Cefpodoxime (200mg)",
    "purpose": "Respiratory/Urine infection",
    "category": "Antibiotic",
    "dosageAdults": "1 tablet every 12 hours",
    "dosageChildren": "",
    "sideEffectsCommon": "Diarrhea",
    "sideEffectsRare": "",
    "contraindications": "Cephalosporin allergy",
    "prescriptionRequired": true,
    "manufacturer": "Mankind",
    "imageUrl": "https://example.com/images/gudcef.jpg"
  },
  {
    "medicineName": "Lulifin Cream",
    "composition": "Luliconazole (1%)",
    "purpose": "Ringworm, Jock itch",
    "category": "Other",
    "dosageAdults": "Apply once daily for 2 weeks",
    "dosageChildren": "",
    "sideEffectsCommon": "Mild irritation",
    "sideEffectsRare": "",
    "contraindications": "None specifically",
    "prescriptionRequired": true,
    "manufacturer": "Sun Pharma",
    "imageUrl": "https://example.com/images/lulifin.jpg"
  },
  {
    "medicineName": "Cabgolin 0.5",
    "composition": "Cabergoline (0.5mg)",
    "purpose": "Stop breast milk production",
    "category": "Other",
    "dosageAdults": "As prescribed (usually minimal dose)",
    "dosageChildren": "",
    "sideEffectsCommon": "Dizziness, nausea",
    "sideEffectsRare": "",
    "contraindications": "High BP post-delivery",
    "prescriptionRequired": true,
    "manufacturer": "Sun Pharma",
    "imageUrl": "https://example.com/images/cabgolin.jpg"
  },
  {
    "medicineName": "Tonoferon Syrup",
    "composition": "Iron + Folic Acid",
    "purpose": "Iron deficiency anemia",
    "category": "Vitamin/Supplement",
    "dosageAdults": "1 teaspoon twice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Black teeth (temporary), black stool",
    "sideEffectsRare": "",
    "contraindications": "Thalassemia",
    "prescriptionRequired": false,
    "manufacturer": "East India Pharma",
    "imageUrl": "https://example.com/images/tonoferon.jpg"
  },
  {
    "medicineName": "Duphaston",
    "composition": "Dydrogesterone (10mg)",
    "purpose": "Infertility, Pregnancy support",
    "category": "Other",
    "dosageAdults": "1 tablet twice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Breast tenderness",
    "sideEffectsRare": "",
    "contraindications": "Undiagnosed bleeding",
    "prescriptionRequired": true,
    "manufacturer": "Abbott",
    "imageUrl": "https://example.com/images/duphaston.jpg"
  },
  {
    "medicineName": "Stamlo 5",
    "composition": "Amlodipine (5mg)",
    "purpose": "High Blood Pressure",
    "category": "Cardiovascular",
    "dosageAdults": "1 tablet daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Swollen feet",
    "sideEffectsRare": "",
    "contraindications": "Low BP",
    "prescriptionRequired": true,
    "manufacturer": "Dr. Reddy's",
    "imageUrl": "https://example.com/images/stamlo.jpg"
  },
  {
    "medicineName": "Drotin Tablet",
    "composition": "Drotaverine (40mg)",
    "purpose": "Stomach spasm/pain",
    "category": "Gastrointestinal",
    "dosageAdults": "1 tablet when needed",
    "dosageChildren": "",
    "sideEffectsCommon": "Nausea",
    "sideEffectsRare": "",
    "contraindications": "Severe heart failure",
    "prescriptionRequired": true,
    "manufacturer": "Walter Bushnell",
    "imageUrl": "https://example.com/images/drotin.jpg"
  },
  {
    "medicineName": "Momate Cream",
    "composition": "Mometasone",
    "purpose": "Eczema, Psoriasis",
    "category": "Other",
    "dosageAdults": "Apply thin layer once daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Skin thinning (long term)",
    "sideEffectsRare": "",
    "contraindications": "Fungal skin infection",
    "prescriptionRequired": true,
    "manufacturer": "Glenmark",
    "imageUrl": "https://example.com/images/momate.jpg"
  },
  {
    "medicineName": "Hepamerz Granules",
    "composition": "L-Ornithine L-Aspartate",
    "purpose": "Liver detoxification",
    "category": "Gastrointestinal",
    "dosageAdults": "Dissolve sachet in water twice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Nausea",
    "sideEffectsRare": "",
    "contraindications": "Severe kidney failure",
    "prescriptionRequired": true,
    "manufacturer": "Win-Medicare",
    "imageUrl": "https://example.com/images/hepamerz.jpg"
  },
  {
    "medicineName": "Hifenac-P",
    "composition": "Aceclofenac + Paracetamol",
    "purpose": "Joint pain, dental pain",
    "category": "Anti-Inflammatory",
    "dosageAdults": "1 tablet after food",
    "dosageChildren": "",
    "sideEffectsCommon": "Gastritis",
    "sideEffectsRare": "",
    "contraindications": "Peptic ulcers",
    "prescriptionRequired": true,
    "manufacturer": "Intas",
    "imageUrl": "https://example.com/images/hifenacp.jpg"
  },
  {
    "medicineName": "Eno Powder",
    "composition": "Sodium Bicarbonate",
    "purpose": "Instant gas relief",
    "category": "Antacid",
    "dosageAdults": "1 sachet in water",
    "dosageChildren": "",
    "sideEffectsCommon": "Burping",
    "sideEffectsRare": "",
    "contraindications": "High blood pressure",
    "prescriptionRequired": false,
    "manufacturer": "GSK",
    "imageUrl": "https://example.com/images/eno.jpg"
  },
  {
    "medicineName": "Ciplar 10",
    "composition": "Propranolol (10mg)",
    "purpose": "Anxiety palpitations, Migraine",
    "category": "Cardiovascular",
    "dosageAdults": "1 tablet twice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Cold hands, nightmares",
    "sideEffectsRare": "",
    "contraindications": "Asthma",
    "prescriptionRequired": true,
    "manufacturer": "Cipla Ltd",
    "imageUrl": "https://example.com/images/ciplar.jpg"
  },
  {
    "medicineName": "Famocid 40",
    "composition": "Famotidine (40mg)",
    "purpose": "Acid Reflux",
    "category": "Antacid",
    "dosageAdults": "1 tablet at bedtime",
    "dosageChildren": "",
    "sideEffectsCommon": "Headache",
    "sideEffectsRare": "",
    "contraindications": "Kidney problems",
    "prescriptionRequired": false,
    "manufacturer": "Sun Pharma",
    "imageUrl": "https://example.com/images/famocid.jpg"
  },
  {
    "medicineName": "Zole-F Ointment",
    "composition": "Miconazole + Fluocinolone",
    "purpose": "Fungal skin infection with itch",
    "category": "Other",
    "dosageAdults": "Apply twice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Skin irritation",
    "sideEffectsRare": "",
    "contraindications": "Tuberculosis of skin",
    "prescriptionRequired": true,
    "manufacturer": "Rallis India",
    "imageUrl": "https://example.com/images/zolef.jpg"
  },
  {
    "medicineName": "Moxikind-CV 625",
    "composition": "Amoxicillin + Clavulanate",
    "purpose": "Infections",
    "category": "Antibiotic",
    "dosageAdults": "1 tablet twice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Loose stools",
    "sideEffectsRare": "",
    "contraindications": "Penicillin allergy",
    "prescriptionRequired": true,
    "manufacturer": "Mankind",
    "imageUrl": "https://example.com/images/moxikind.jpg"
  },
  {
    "medicineName": "Itroplus 100",
    "composition": "Itraconazole (100mg)",
    "purpose": "Fungal infections (Nails/Skin)",
    "category": "Other",
    "dosageAdults": "1 capsule after full meal",
    "dosageChildren": "",
    "sideEffectsCommon": "Nausea, liver enzyme spike",
    "sideEffectsRare": "",
    "contraindications": "Heart failure history",
    "prescriptionRequired": true,
    "manufacturer": "Macleods",
    "imageUrl": "https://example.com/images/itroplus.jpg"
  },
  {
    "medicineName": "Unwanted 72",
    "composition": "Levonorgestrel (1.5mg)",
    "purpose": "Emergency Contraceptive",
    "category": "Other",
    "dosageAdults": "Single dose within 72 hrs",
    "dosageChildren": "",
    "sideEffectsCommon": "Period delay, nausea",
    "sideEffectsRare": "",
    "contraindications": "Existing pregnancy",
    "prescriptionRequired": false,
    "manufacturer": "Mankind",
    "imageUrl": "https://example.com/images/unwanted72.jpg"
  },
  {
    "medicineName": "Daflon 500",
    "composition": "Diosmin + Hesperidin",
    "purpose": "Piles (Hemorrhoids), Varicose veins",
    "category": "Other",
    "dosageAdults": "1 tablet twice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Stomach pain",
    "sideEffectsRare": "",
    "contraindications": "None specifically",
    "prescriptionRequired": true,
    "manufacturer": "Serdia",
    "imageUrl": "https://example.com/images/daflon.jpg"
  },
  {
    "medicineName": "Minipress XL 5",
    "composition": "Prazosin (5mg)",
    "purpose": "High BP",
    "category": "Antihypertensive",
    "dosageAdults": "1 tablet at bedtime",
    "dosageChildren": "",
    "sideEffectsCommon": "Dizziness",
    "sideEffectsRare": "",
    "contraindications": "Cataract surgery (inform doctor)",
    "prescriptionRequired": true,
    "manufacturer": "Pfizer Ltd",
    "imageUrl": "https://example.com/images/minipress.jpg"
  },
  {
    "medicineName": "Telmikind 40",
    "composition": "Telmisartan (40mg)",
    "purpose": "BP Control",
    "category": "Antihypertensive",
    "dosageAdults": "1 tablet daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Back pain",
    "sideEffectsRare": "",
    "contraindications": "Pregnancy",
    "prescriptionRequired": true,
    "manufacturer": "Mankind",
    "imageUrl": "https://example.com/images/telmikind.jpg"
  },
  {
    "medicineName": "Potklor Syrup",
    "composition": "Potassium Chloride",
    "purpose": "Potassium deficiency",
    "category": "Vitamin/Supplement",
    "dosageAdults": "Dilute in water and drink",
    "dosageChildren": "",
    "sideEffectsCommon": "Stomach upset",
    "sideEffectsRare": "",
    "contraindications": "High potassium levels",
    "prescriptionRequired": true,
    "manufacturer": "Pfizer Ltd",
    "imageUrl": "https://example.com/images/potklor.jpg"
  },
  {
    "medicineName": "Candid-B Cream",
    "composition": "Clotrimazole + Beclomethasone",
    "purpose": "Fungal infection with swelling",
    "category": "Other",
    "dosageAdults": "Apply twice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Thinning of skin",
    "sideEffectsRare": "",
    "contraindications": "Viral skin infections",
    "prescriptionRequired": true,
    "manufacturer": "Glenmark",
    "imageUrl": "https://example.com/images/candidb.jpg"
  },
  {
    "medicineName": "Susten 200",
    "composition": "Progesterone (Natural Micronized)",
    "purpose": "Pregnancy support",
    "category": "Other",
    "dosageAdults": "Oral or Vaginal as prescribed",
    "dosageChildren": "",
    "sideEffectsCommon": "Dizziness, sleepiness",
    "sideEffectsRare": "",
    "contraindications": "Breast cancer",
    "prescriptionRequired": true,
    "manufacturer": "Sun Pharma",
    "imageUrl": "https://example.com/images/susten.jpg"
  },
  {
    "medicineName": "Rablet-D",
    "composition": "Rabeprazole + Domperidone",
    "purpose": "Severe acidity",
    "category": "Antacid",
    "dosageAdults": "1 capsule before breakfast",
    "dosageChildren": "",
    "sideEffectsCommon": "Dry mouth",
    "sideEffectsRare": "",
    "contraindications": "Bowel obstruction",
    "prescriptionRequired": true,
    "manufacturer": "Lupin",
    "imageUrl": "https://example.com/images/rabletd.jpg"
  },
  {
    "medicineName": "Bactroban Ointment",
    "composition": "Mupirocin (2%)",
    "purpose": "Impetigo (Skin infection)",
    "category": "Antibiotic",
    "dosageAdults": "Apply 3 times daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Burning sensation",
    "sideEffectsRare": "",
    "contraindications": "Burn wounds",
    "prescriptionRequired": true,
    "manufacturer": "GSK",
    "imageUrl": "https://example.com/images/bactroban.jpg"
  },
  {
    "medicineName": "Sorbiline Syrup",
    "composition": "Tricholine Citrate + Sorbitol",
    "purpose": "Fatty liver, Constipation",
    "category": "Gastrointestinal",
    "dosageAdults": "10ml before meals",
    "dosageChildren": "",
    "sideEffectsCommon": "Loose motion",
    "sideEffectsRare": "",
    "contraindications": "Fructose intolerance",
    "prescriptionRequired": false,
    "manufacturer": "Franco-Indian",
    "imageUrl": "https://example.com/images/sorbiline.jpg"
  },
  {
    "medicineName": "Ibugesic Plus",
    "composition": "Ibuprofen + Paracetamol",
    "purpose": "High fever, Pain",
    "category": "Anti-Inflammatory",
    "dosageAdults": "1 tablet every 6-8 hours",
    "dosageChildren": "",
    "sideEffectsCommon": "Heartburn",
    "sideEffectsRare": "",
    "contraindications": "Dengue (Avoid Ibuprofen)",
    "prescriptionRequired": false,
    "manufacturer": "Cipla Ltd",
    "imageUrl": "https://example.com/images/ibugesic.jpg"
  },
  {
    "medicineName": "Arkamin",
    "composition": "Clonidine (100mcg)",
    "purpose": "High BP (Resistant)",
    "category": "Antihypertensive",
    "dosageAdults": "1 tablet twice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Dry mouth, sedation",
    "sideEffectsRare": "",
    "contraindications": "Depression",
    "prescriptionRequired": true,
    "manufacturer": "Torrent Pharma",
    "imageUrl": "https://example.com/images/arkamin.jpg"
  },
  {
    "medicineName": "Esgipyrin",
    "composition": "Diclofenac + Paracetamol",
    "purpose": "Pain relief",
    "category": "Anti-Inflammatory",
    "dosageAdults": "1 tablet after food",
    "dosageChildren": "",
    "sideEffectsCommon": "Stomach pain",
    "sideEffectsRare": "",
    "contraindications": "Heart surgery recovery",
    "prescriptionRequired": true,
    "manufacturer": "Abbott",
    "imageUrl": "https://example.com/images/esgipyrin.jpg"
  },
  {
    "medicineName": "Asthalin Syrup",
    "composition": "Salbutamol (2mg/5ml)",
    "purpose": "Asthma cough in kids",
    "category": "Respiratory",
    "dosageAdults": "5ml thrice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Shaking, hyperactivity",
    "sideEffectsRare": "",
    "contraindications": "Cardiac arrhythmia",
    "prescriptionRequired": true,
    "manufacturer": "Cipla Ltd",
    "imageUrl": "https://example.com/images/asthalin_syp.jpg"
  },
  {
    "medicineName": "Sumo Tablet",
    "composition": "Nimesulide + Paracetamol",
    "purpose": "Fever, Body ache",
    "category": "Anti-Inflammatory",
    "dosageAdults": "1 tablet twice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Liver toxicity risk",
    "sideEffectsRare": "",
    "contraindications": "Children below 12 years",
    "prescriptionRequired": true,
    "manufacturer": "Alkem",
    "imageUrl": "https://example.com/images/sumo.jpg"
  },
  {
    "medicineName": "Sysfol",
    "composition": "Folic Acid (5mg)",
    "purpose": "Pregnancy supplement",
    "category": "Vitamin/Supplement",
    "dosageAdults": "1 tablet daily",
    "dosageChildren": "",
    "sideEffectsCommon": "None usually",
    "sideEffectsRare": "",
    "contraindications": "Undiagnosed anemia",
    "prescriptionRequired": false,
    "manufacturer": "Systopic",
    "imageUrl": "https://example.com/images/sysfol.jpg"
  },
  {
    "medicineName": "Betadine Gargle",
    "composition": "Povidone Iodine (2%)",
    "purpose": "Sore throat",
    "category": "Other",
    "dosageAdults": "Gargle with 10ml diluted in water",
    "dosageChildren": "",
    "sideEffectsCommon": "Taste alteration",
    "sideEffectsRare": "",
    "contraindications": "Thyroid disorders",
    "prescriptionRequired": false,
    "manufacturer": "Win-Medicare",
    "imageUrl": "https://example.com/images/betadine_gargle.jpg"
  },
  {
    "medicineName": "Primolut-N",
    "composition": "Norethisterone (5mg)",
    "purpose": "Period delay",
    "category": "Other",
    "dosageAdults": "1 tablet twice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Headache",
    "sideEffectsRare": "",
    "contraindications": "Pregnancy",
    "prescriptionRequired": true,
    "manufacturer": "Zydus",
    "imageUrl": "https://example.com/images/primolut.jpg"
  },
  {
    "medicineName": "Ondem 4",
    "composition": "Ondansetron (4mg)",
    "purpose": "Nausea and Vomiting",
    "category": "Other",
    "dosageAdults": "1 tablet when needed (dissolve on tongue)",
    "dosageChildren": "",
    "sideEffectsCommon": "Headache, constipation",
    "sideEffectsRare": "",
    "contraindications": "Heart rhythm disorders (QT prolongation)",
    "prescriptionRequired": true,
    "manufacturer": "Alkem Laboratories",
    "imageUrl": "https://example.com/images/ondem4.jpg"
  },
  {
    "medicineName": "Zifi 200",
    "composition": "Cefixime (200mg)",
    "purpose": "Ear, Throat, UTI infections",
    "category": "Antibiotic",
    "dosageAdults": "1 tablet twice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Diarrhea, stomach pain",
    "sideEffectsRare": "",
    "contraindications": "Cephalosporin allergy",
    "prescriptionRequired": true,
    "manufacturer": "FDC Ltd",
    "imageUrl": "https://example.com/images/zifi200.jpg"
  },
  {
    "medicineName": "Folvite",
    "composition": "Folic Acid (5mg)",
    "purpose": "Anemia, Pregnancy supplement",
    "category": "Vitamin/Supplement",
    "dosageAdults": "1 tablet daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Nausea (rare)",
    "sideEffectsRare": "",
    "contraindications": "Undiagnosed B12 deficiency",
    "prescriptionRequired": false,
    "manufacturer": "Wyeth (Pfizer)",
    "imageUrl": "https://example.com/images/folvite.jpg"
  },
  {
    "medicineName": "Doxy-1 L-DR",
    "composition": "Doxycycline + Lactobacillus",
    "purpose": "Acne, Bacterial infections",
    "category": "Antibiotic",
    "dosageAdults": "1 capsule daily after food",
    "dosageChildren": "",
    "sideEffectsCommon": "Sun sensitivity, throat burn",
    "sideEffectsRare": "",
    "contraindications": "Pregnancy, Children <8 years",
    "prescriptionRequired": true,
    "manufacturer": "USV Pvt Ltd",
    "imageUrl": "https://example.com/images/doxy1.jpg"
  },
  {
    "medicineName": "Nexito 10",
    "composition": "Escitalopram (10mg)",
    "purpose": "Depression, Anxiety",
    "category": "Other",
    "dosageAdults": "1 tablet daily (Do not stop suddenly)",
    "dosageChildren": "",
    "sideEffectsCommon": "Sexual dysfunction, insomnia",
    "sideEffectsRare": "",
    "contraindications": "MAO Inhibitor use",
    "prescriptionRequired": true,
    "manufacturer": "Sun Pharma",
    "imageUrl": "https://example.com/images/nexito10.jpg"
  },
  {
    "medicineName": "Perinorm",
    "composition": "Metoclopramide (10mg)",
    "purpose": "Nausea, Heartburn",
    "category": "Other",
    "dosageAdults": "1 tablet before meals",
    "dosageChildren": "",
    "sideEffectsCommon": "Restlessness, drowsiness",
    "sideEffectsRare": "",
    "contraindications": "Gastrointestinal bleeding",
    "prescriptionRequired": true,
    "manufacturer": "Ipca Laboratories",
    "imageUrl": "https://example.com/images/perinorm.jpg"
  },
  {
    "medicineName": "Omnacortil 10",
    "composition": "Prednisolone (10mg)",
    "purpose": "Severe allergy, Asthma",
    "category": "Other",
    "dosageAdults": "As per strict doctor prescription",
    "dosageChildren": "",
    "sideEffectsCommon": "Weight gain, mood changes",
    "sideEffectsRare": "",
    "contraindications": "Systemic fungal infections",
    "prescriptionRequired": true,
    "manufacturer": "Macleods",
    "imageUrl": "https://example.com/images/omnacortil.jpg"
  },
  {
    "medicineName": "Aristozyme Liquid",
    "composition": "Diastase + Pepsin",
    "purpose": "Indigestion, Loss of appetite",
    "category": "Gastrointestinal",
    "dosageAdults": "10ml after meals",
    "dosageChildren": "",
    "sideEffectsCommon": "Abdominal pain (rare)",
    "sideEffectsRare": "",
    "contraindications": "None specifically",
    "prescriptionRequired": false,
    "manufacturer": "Aristo",
    "imageUrl": "https://example.com/images/aristozyme.jpg"
  },
  {
    "medicineName": "Looz Syrup",
    "composition": "Lactulose",
    "purpose": "Constipation, Liver encephalopathy",
    "category": "Gastrointestinal",
    "dosageAdults": "15-30ml at bedtime",
    "dosageChildren": "",
    "sideEffectsCommon": "Gas, bloating",
    "sideEffectsRare": "",
    "contraindications": "Galactosemia",
    "prescriptionRequired": false,
    "manufacturer": "Intas",
    "imageUrl": "https://example.com/images/looz.jpg"
  },
  {
    "medicineName": "Clonotril 0.5",
    "composition": "Clonazepam (0.5mg)",
    "purpose": "Anxiety, Seizures",
    "category": "Other",
    "dosageAdults": "1 tablet at night (Habit forming)",
    "dosageChildren": "",
    "sideEffectsCommon": "Sedation, memory issues",
    "sideEffectsRare": "",
    "contraindications": "Glaucoma, liver disease",
    "prescriptionRequired": true,
    "manufacturer": "Torrent Pharma",
    "imageUrl": "https://example.com/images/clonotril.jpg"
  },
  {
    "medicineName": "Fourderm",
    "composition": "Clobetasol + Neomycin + Miconazole",
    "purpose": "Mixed skin infections",
    "category": "Other",
    "dosageAdults": "Apply thinly twice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Skin thinning",
    "sideEffectsRare": "",
    "contraindications": "Viral skin infections",
    "prescriptionRequired": true,
    "manufacturer": "Cipla Ltd",
    "imageUrl": "https://example.com/images/fourderm.jpg"
  },
  {
    "medicineName": "Bandy 400",
    "composition": "Albendazole (400mg)",
    "purpose": "Deworming (Parasites)",
    "category": "Other",
    "dosageAdults": "1 tablet chewable (Single dose)",
    "dosageChildren": "",
    "sideEffectsCommon": "Stomach pain",
    "sideEffectsRare": "",
    "contraindications": "Pregnancy (Teratogenic)",
    "prescriptionRequired": true,
    "manufacturer": "Mankind",
    "imageUrl": "https://example.com/images/bandy.jpg"
  },
  {
    "medicineName": "HCQS 200",
    "composition": "Hydroxychloroquine (200mg)",
    "purpose": "Rheumatoid Arthritis, Lupus",
    "category": "Other",
    "dosageAdults": "1 tablet with milk/food",
    "dosageChildren": "",
    "sideEffectsCommon": "Vision changes (Retinopathy)",
    "sideEffectsRare": "",
    "contraindications": "Maculopathy eye disease",
    "prescriptionRequired": true,
    "manufacturer": "Ipca Laboratories",
    "imageUrl": "https://example.com/images/hcqs.jpg"
  },
  {
    "medicineName": "Montair 10",
    "composition": "Montelukast (10mg)",
    "purpose": "Asthma prevention, Allergic rhinitis",
    "category": "Respiratory",
    "dosageAdults": "1 tablet in the evening",
    "dosageChildren": "",
    "sideEffectsCommon": "Mood changes, nightmares",
    "sideEffectsRare": "",
    "contraindications": "Acute asthma attack (Not for rescue)",
    "prescriptionRequired": true,
    "manufacturer": "Cipla Ltd",
    "imageUrl": "https://example.com/images/montair.jpg"
  },
  {
    "medicineName": "Janumet 50/500",
    "composition": "Sitagliptin + Metformin",
    "purpose": "Type 2 Diabetes",
    "category": "Antidiabetic",
    "dosageAdults": "1 tablet twice daily with meals",
    "dosageChildren": "",
    "sideEffectsCommon": "Pancreatitis risk, gas",
    "sideEffectsRare": "",
    "contraindications": "Kidney dysfunction",
    "prescriptionRequired": true,
    "manufacturer": "MSD",
    "imageUrl": "https://example.com/images/janumet.jpg"
  },
  {
    "medicineName": "Zedex Cough Syrup",
    "composition": "Bromhexine + Dextromethorphan",
    "purpose": "Dry and Wet cough mix",
    "category": "Cough & Cold",
    "dosageAdults": "10ml thrice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Sleepiness",
    "sideEffectsRare": "",
    "contraindications": "Severe asthma",
    "prescriptionRequired": false,
    "manufacturer": "Wockhardt",
    "imageUrl": "https://example.com/images/zedex.jpg"
  },
  {
    "medicineName": "Moov Spray",
    "composition": "Diclofenac + Wintergreen Oil",
    "purpose": "Back pain, Muscle spray",
    "category": "Anti-Inflammatory",
    "dosageAdults": "Spray on affected area",
    "dosageChildren": "",
    "sideEffectsCommon": "Skin redness",
    "sideEffectsRare": "",
    "contraindications": "Open wounds",
    "prescriptionRequired": false,
    "manufacturer": "Reckitt Benckiser",
    "imageUrl": "https://example.com/images/moov.jpg"
  },
  {
    "medicineName": "Livogen Z",
    "composition": "Iron + Zinc + Folic Acid",
    "purpose": "Iron deficiency anemia",
    "category": "Vitamin/Supplement",
    "dosageAdults": "1 tablet after lunch",
    "dosageChildren": "",
    "sideEffectsCommon": "Black stools, constipation",
    "sideEffectsRare": "",
    "contraindications": "Hemochromatosis (Iron overload)",
    "prescriptionRequired": false,
    "manufacturer": "P&G Health",
    "imageUrl": "https://example.com/images/livogen.jpg"
  },
  {
    "medicineName": "Telvas 40",
    "composition": "Telmisartan (40mg)",
    "purpose": "High Blood Pressure",
    "category": "Antihypertensive",
    "dosageAdults": "1 tablet daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Dizziness",
    "sideEffectsRare": "",
    "contraindications": "Pregnancy (Category D)",
    "prescriptionRequired": true,
    "manufacturer": "Aristo",
    "imageUrl": "https://example.com/images/telvas.jpg"
  },
  {
    "medicineName": "Mobizox",
    "composition": "Diclofenac + Paracetamol + Chlorzoxazone",
    "purpose": "Muscle spasm and pain",
    "category": "Other",
    "dosageAdults": "1 tablet twice daily after food",
    "dosageChildren": "",
    "sideEffectsCommon": "Drowsiness, stomach pain",
    "sideEffectsRare": "",
    "contraindications": "Liver disease",
    "prescriptionRequired": true,
    "manufacturer": "Sun Pharma",
    "imageUrl": "https://example.com/images/mobizox.jpg"
  },
  {
    "medicineName": "Tenlimac 20",
    "composition": "Teneligliptin (20mg)",
    "purpose": "Type 2 Diabetes",
    "category": "Antidiabetic",
    "dosageAdults": "1 tablet daily before breakfast",
    "dosageChildren": "",
    "sideEffectsCommon": "Hypoglycemia, constipation",
    "sideEffectsRare": "",
    "contraindications": "Severe ketosis",
    "prescriptionRequired": true,
    "manufacturer": "Macleods",
    "imageUrl": "https://example.com/images/tenlimac.jpg"
  },
  {
    "medicineName": "Diane-35",
    "composition": "Cyproterone + Ethinyl Estradiol",
    "purpose": "PCOS, Acne, Contraception",
    "category": "Other",
    "dosageAdults": "1 tablet daily for 21 days",
    "dosageChildren": "",
    "sideEffectsCommon": "Mood swings, blood clot risk",
    "sideEffectsRare": "",
    "contraindications": "History of thrombosis (clots)",
    "prescriptionRequired": true,
    "manufacturer": "Bayer",
    "imageUrl": "https://example.com/images/diane35.jpg"
  },
  {
    "medicineName": "Meftal P Suspension",
    "composition": "Mefenamic Acid",
    "purpose": "Fever and Pain in children",
    "category": "Anti-Inflammatory",
    "dosageAdults": "As per weight (Approx 5ml)",
    "dosageChildren": "",
    "sideEffectsCommon": "Nausea",
    "sideEffectsRare": "",
    "contraindications": "Dehydrated children",
    "prescriptionRequired": false,
    "manufacturer": "Blue Cross",
    "imageUrl": "https://example.com/images/meftalp.jpg"
  },
  {
    "medicineName": "Voveran Emulgel",
    "composition": "Diclofenac Diethylamine",
    "purpose": "Joint pain, inflammation",
    "category": "Anti-Inflammatory",
    "dosageAdults": "Rub gently on pain area",
    "dosageChildren": "",
    "sideEffectsCommon": "Dermatitis (rare)",
    "sideEffectsRare": "",
    "contraindications": "Open skin cuts",
    "prescriptionRequired": false,
    "manufacturer": "Novartis",
    "imageUrl": "https://example.com/images/voveran_gel.jpg"
  },
  {
    "medicineName": "Human Mixtard 30/70",
    "composition": "Insulin Isophane",
    "purpose": "Diabetes Mellitus",
    "category": "Antidiabetic",
    "dosageAdults": "Inject subcutaneously before meals",
    "dosageChildren": "",
    "sideEffectsCommon": "Hypoglycemia, weight gain",
    "sideEffectsRare": "",
    "contraindications": "Hypoglycemia episodes",
    "prescriptionRequired": true,
    "manufacturer": "Novo Nordisk",
    "imageUrl": "https://example.com/images/mixtard.jpg"
  },
  {
    "medicineName": "Ciplox-TZ",
    "composition": "Ciprofloxacin + Tinidazole",
    "purpose": "Stomach infection, Diarrhea",
    "category": "Antibiotic",
    "dosageAdults": "1 tablet twice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Metallic taste, nausea",
    "sideEffectsRare": "",
    "contraindications": "Alcohol consumption",
    "prescriptionRequired": true,
    "manufacturer": "Cipla Ltd",
    "imageUrl": "https://example.com/images/ciploxtz.jpg"
  },
  {
    "medicineName": "A to Z NS",
    "composition": "Multivitamins + Minerals",
    "purpose": "General weakness",
    "category": "Vitamin/Supplement",
    "dosageAdults": "1 tablet daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Yellow urine",
    "sideEffectsRare": "",
    "contraindications": "None specifically",
    "prescriptionRequired": false,
    "manufacturer": "Alkem",
    "imageUrl": "https://example.com/images/atoz.jpg"
  },
  {
    "medicineName": "Etoshine 90",
    "composition": "Etoricoxib (90mg)",
    "purpose": "Severe Arthritis pain",
    "category": "Anti-Inflammatory",
    "dosageAdults": "1 tablet daily",
    "dosageChildren": "",
    "sideEffectsCommon": "High BP, Palpitations",
    "sideEffectsRare": "",
    "contraindications": "Heart disease history",
    "prescriptionRequired": true,
    "manufacturer": "Sun Pharma",
    "imageUrl": "https://example.com/images/etoshine.jpg"
  },
  {
    "medicineName": "Panderm ++",
    "composition": "Clobetasol + Neomycin + Miconazole",
    "purpose": "Skin infections",
    "category": "Other",
    "dosageAdults": "Apply twice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Skin thinning",
    "sideEffectsRare": "",
    "contraindications": "Face application (long term)",
    "prescriptionRequired": true,
    "manufacturer": "Macleods",
    "imageUrl": "https://example.com/images/panderm.jpg"
  },
  {
    "medicineName": "Iodex Balm",
    "composition": "Iodine + Methyl Salicylate",
    "purpose": "Muscle pain, cold",
    "category": "Other",
    "dosageAdults": "Apply on area",
    "dosageChildren": "",
    "sideEffectsCommon": "Staining of clothes",
    "sideEffectsRare": "",
    "contraindications": "Broken skin",
    "prescriptionRequired": false,
    "manufacturer": "GSK",
    "imageUrl": "https://example.com/images/iodex.jpg"
  },
  {
    "medicineName": "Nurokind-LC",
    "composition": "Levocarnitine + Mecobalamin",
    "purpose": "Nerve damage, Diabetic neuropathy",
    "category": "Vitamin/Supplement",
    "dosageAdults": "1 tablet daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Nausea",
    "sideEffectsRare": "",
    "contraindications": "None specifically",
    "prescriptionRequired": true,
    "manufacturer": "Mankind",
    "imageUrl": "https://example.com/images/nurokind.jpg"
  },
  {
    "medicineName": "Deriva-CMS",
    "composition": "Adapalene + Clindamycin",
    "purpose": "Acne (Pimples)",
    "category": "Other",
    "dosageAdults": "Apply at night on pimples",
    "dosageChildren": "",
    "sideEffectsCommon": "Skin peeling, dryness",
    "sideEffectsRare": "",
    "contraindications": "Sun exposure (Increases sensitivity)",
    "prescriptionRequired": true,
    "manufacturer": "Glenmark",
    "imageUrl": "https://example.com/images/deriva.jpg"
  },
  {
    "medicineName": "Finecef-O 200",
    "composition": "Cefixime + Ofloxacin",
    "purpose": "Typhoid, Resistant infections",
    "category": "Antibiotic",
    "dosageAdults": "1 tablet twice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Stomach upset",
    "sideEffectsRare": "",
    "contraindications": "Epilepsy",
    "prescriptionRequired": true,
    "manufacturer": "Abbott",
    "imageUrl": "https://example.com/images/finecefo.jpg"
  },
  {
    "medicineName": "Lantus Injection",
    "composition": "Insulin Glargine",
    "purpose": "Diabetes (Long acting)",
    "category": "Antidiabetic",
    "dosageAdults": "Once daily subcutaneous",
    "dosageChildren": "",
    "sideEffectsCommon": "Low blood sugar",
    "sideEffectsRare": "",
    "contraindications": "Hypoglycemia",
    "prescriptionRequired": true,
    "manufacturer": "Sanofi",
    "imageUrl": "https://example.com/images/lantus.jpg"
  },
  {
    "medicineName": "Paracip 650",
    "composition": "Paracetamol (650mg)",
    "purpose": "High Fever",
    "category": "Painkiller",
    "dosageAdults": "1 tablet every 6 hours",
    "dosageChildren": "",
    "sideEffectsCommon": "Liver toxicity (overdose)",
    "sideEffectsRare": "",
    "contraindications": "Liver failure",
    "prescriptionRequired": false,
    "manufacturer": "Cipla Ltd",
    "imageUrl": "https://example.com/images/paracip.jpg"
  },
  {
    "medicineName": "Enerzal Powder",
    "composition": "Glucose + Electrolytes",
    "purpose": "Dehydration, Energy",
    "category": "Other",
    "dosageAdults": "Mix in water and drink",
    "dosageChildren": "",
    "sideEffectsCommon": "None",
    "sideEffectsRare": "",
    "contraindications": "Uncontrolled Diabetes",
    "prescriptionRequired": false,
    "manufacturer": "FDC Ltd",
    "imageUrl": "https://example.com/images/enerzal.jpg"
  },
  {
    "medicineName": "Saaz 500",
    "composition": "Sulfasalazine (500mg)",
    "purpose": "Ulcerative Colitis, Rheumatoid Arthritis",
    "category": "Anti-Inflammatory",
    "dosageAdults": "1 tablet after meals",
    "dosageChildren": "",
    "sideEffectsCommon": "Orange urine/skin, nausea",
    "sideEffectsRare": "",
    "contraindications": "Sulfa allergy",
    "prescriptionRequired": true,
    "manufacturer": "Ipca Laboratories",
    "imageUrl": "https://example.com/images/saaz.jpg"
  },
  {
    "medicineName": "Defcort 6",
    "composition": "Deflazacort (6mg)",
    "purpose": "Autoimmune conditions",
    "category": "Other",
    "dosageAdults": "As prescribed",
    "dosageChildren": "",
    "sideEffectsCommon": "Weight gain, puffy face",
    "sideEffectsRare": "",
    "contraindications": "Systemic infection",
    "prescriptionRequired": true,
    "manufacturer": "Macleods",
    "imageUrl": "https://example.com/images/defcort.jpg"
  },
  {
    "medicineName": "Vasograin",
    "composition": "Ergotamine + Caffeine + Paracetamol",
    "purpose": "Migraine attacks",
    "category": "Other",
    "dosageAdults": "1 tablet at onset of headache",
    "dosageChildren": "",
    "sideEffectsCommon": "Nausea, restlessness",
    "sideEffectsRare": "",
    "contraindications": "Heart disease, pregnancy",
    "prescriptionRequired": true,
    "manufacturer": "Cadila",
    "imageUrl": "https://example.com/images/vasograin.jpg"
  },
  {
    "medicineName": "Grilinctus CD",
    "composition": "Codeine + Chlorpheniramine",
    "purpose": "Dry painful cough",
    "category": "Cough & Cold",
    "dosageAdults": "5ml thrice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Constipation, drowsiness, addiction",
    "sideEffectsRare": "",
    "contraindications": "Asthma, Respiratory depression",
    "prescriptionRequired": true,
    "manufacturer": "Franco-Indian",
    "imageUrl": "https://example.com/images/grilinctus_cd.jpg"
  },
  {
    "medicineName": "Rozucor 10",
    "composition": "Rosuvastatin (10mg)",
    "purpose": "Cholesterol",
    "category": "Cardiovascular",
    "dosageAdults": "1 tablet at night",
    "dosageChildren": "",
    "sideEffectsCommon": "Muscle pain",
    "sideEffectsRare": "",
    "contraindications": "Active liver disease",
    "prescriptionRequired": true,
    "manufacturer": "Torrent Pharma",
    "imageUrl": "https://example.com/images/rozucor.jpg"
  },
  {
    "medicineName": "Lobate-GM",
    "composition": "Clobetasol + Neomycin + Miconazole",
    "purpose": "Skin Infection",
    "category": "Other",
    "dosageAdults": "Apply twice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Itching",
    "sideEffectsRare": "",
    "contraindications": "Viral infection",
    "prescriptionRequired": true,
    "manufacturer": "Abbott",
    "imageUrl": "https://example.com/images/lobategm.jpg"
  },
  {
    "medicineName": "Phensedyl",
    "composition": "Dextromethorphan + CPM",
    "purpose": "Dry Cough",
    "category": "Cough & Cold",
    "dosageAdults": "5ml thrice daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Sedation",
    "sideEffectsRare": "",
    "contraindications": "Driving",
    "prescriptionRequired": true,
    "manufacturer": "Abbott",
    "imageUrl": "https://example.com/images/phensedyl.jpg"
  },
  {
    "medicineName": "Gemcal",
    "composition": "Calcium Carbonate + Calcitriol",
    "purpose": "Bone strength, Osteoporosis",
    "category": "Vitamin/Supplement",
    "dosageAdults": "1 capsule daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Constipation",
    "sideEffectsRare": "",
    "contraindications": "Hypercalcemia",
    "prescriptionRequired": false,
    "manufacturer": "Alkem",
    "imageUrl": "https://example.com/images/gemcal.jpg"
  },
  {
    "medicineName": "Probiplus",
    "composition": "Probiotics (Lactobacillus)",
    "purpose": "Restore gut bacteria after antibiotics",
    "category": "Other",
    "dosageAdults": "1 capsule daily",
    "dosageChildren": "",
    "sideEffectsCommon": "Bloating (initial)",
    "sideEffectsRare": "",
    "contraindications": "None",
    "prescriptionRequired": false,
    "manufacturer": "Mankind",
    "imageUrl": "https://example.com/images/probiplus.jpg"
  },
  {
    "medicineName": "Imodium",
    "composition": "Loperamide (2mg)",
    "purpose": "Loose motions (Diarrhea)",
    "category": "Gastrointestinal",
    "dosageAdults": "2 tablets initially, then 1 after each loose stool",
    "dosageChildren": "",
    "sideEffectsCommon": "Constipation, cramps",
    "sideEffectsRare": "",
    "contraindications": "Dysentery (Blood in stool)",
    "prescriptionRequired": false,
    "manufacturer": "Janssen",
    "imageUrl": "https://example.com/images/imodium.jpg"
  },
  {
    "medicineName": "Dytor Plus 10",
    "composition": "Torsemide + Spironolactone",
    "purpose": "Swelling (Edema)",
    "category": "Cardiovascular",
    "dosageAdults": "1 tablet morning",
    "dosageChildren": "",
    "sideEffectsCommon": "Dehydration, electrolyte imbalance",
    "sideEffectsRare": "",
    "contraindications": "Kidney failure",
    "prescriptionRequired": true,
    "manufacturer": "Cipla Ltd",
    "imageUrl": "https://example.com/images/dytorplus.jpg"
  },
  {
    "medicineName": "Yasmin",
    "composition": "Drospirenone + Ethinyl Estradiol",
    "purpose": "Contraception",
    "category": "Other",
    "dosageAdults": "1 tablet daily for 21 days",
    "dosageChildren": "",
    "sideEffectsCommon": "Nausea, headache",
    "sideEffectsRare": "",
    "contraindications": "Blood clotting disorders",
    "prescriptionRequired": true,
    "manufacturer": "Bayer",
    "imageUrl": "https://example.com/images/yasmin.jpg"
  },
  {
    "medicineName": "Thyrox 100",
    "composition": "Thyroxine Sodium (100mcg)",
    "purpose": "Hypothyroidism",
    "category": "Other",
    "dosageAdults": "1 tablet empty stomach morning",
    "dosageChildren": "",
    "sideEffectsCommon": "Heat intolerance (if dose high)",
    "sideEffectsRare": "",
    "contraindications": "Heart attack (recent)",
    "prescriptionRequired": true,
    "manufacturer": "Macleods",
    "imageUrl": "https://example.com/images/thyrox.jpg"
  },
  {
    "medicineName": "Tryptomer 10",
    "composition": "Amitriptyline (10mg)",
    "purpose": "Nerve pain, Migraine prevention, Sleep",
    "category": "Other",
    "dosageAdults": "1 tablet at bedtime",
    "dosageChildren": "",
    "sideEffectsCommon": "Dry mouth, drowsiness",
    "sideEffectsRare": "",
    "contraindications": "Heart block recovery",
    "prescriptionRequired": true,
    "manufacturer": "Wockhardt",
    "imageUrl": "https://example.com/images/tryptomer.jpg"
  }
];

async function seedDatabase() {
  try {
    // Connect to MongoDB
    await mongoose.connect(process.env.DB_URL);
    console.log('Connected to MongoDB');

    // Clear existing data
    await MedDatabase.deleteMany({});
    console.log('Cleared existing medicine database');

    // Insert new data
    const result = await MedDatabase.insertMany(medicinesData);
    console.log(`Successfully inserted ${result.length} medicines`);

    console.log('\nSeeding completed successfully!');
    process.exit(0);
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
}

seedDatabase();
